### ISSUE TITLE
Write docker-specific options to its own .cnf file like it happens on mysql image

### ISSUE THREAD

**Issue by elisiano** [docker-library/mariadb#100]
Would it make sense to write docker-specific options into a separate .cnf file like described at https://github.com/docker-library/mysql/pull/199 ?

This would make it easier to reverse the `skip-name-resolve` option which is baked into the image.

**Comment by yosifkit** [comment]
Sorry we missed this; we really should do that. :disappointed:

I'll go make a PR!
