### ISSUE TITLE
Create Custom MariaDB Docker image

### ISSUE THREAD

**Issue by w7089** [docker-library/mariadb#103]
I would like to create new custom image of MariaDB out of official image

The image will be created from official Dockerfile

Custom Dockerfile will be without the last line - 

> CMD ["mysqld"]

 Running `docker build -t "mariaoff" . `fails with error on step 4 :

> Step 4/19 : RUN set -x && apt-get update && apt-get install -y --no-install-recommends ca-certificates wget && rm -rf /var/lib/apt/lists/* && wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture)" && wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$(dpkg --print-architecture).asc" && export GNUPGHOME="$(mktemp -d)" && gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4 && gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu && rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc && chmod +x /usr/local/bin/gosu && gosu nobody true && apt-get purge -y --auto-remove ca-certificates wget ---> Running in ada842f657d0 + apt-get update Ign http://security.debian.org jessie/updates InRelease Ign http://deb.debian.org jessie InRelease Ign http://deb.debian.org jessie-updates InRelease Ign http://security.debian.org jessie/updates Release.gpg Ign http://deb.debian.org jessie Release.gpg Ign http://deb.debian.org jessie-updates Release.gpg Ign http://security.debian.org jessie/updates Release Ign http://deb.debian.org jessie Release Ign http://deb.debian.org jessie-updates Release Err http://security.debian.org jessie/updates/main amd64 Packages Err http://deb.debian.org jessie/main amd64 Packages Err http://deb.debian.org jessie-updates/main amd64 Packages Err http://security.debian.org jessie/updates/main amd64 Packages Err http://deb.debian.org jessie/main amd64 Packages Err http://deb.debian.org jessie/main amd64 Packages Err http://deb.debian.org jessie-updates/main amd64 Packages Err http://deb.debian.org jessie/main amd64 Packages Err http://deb.debian.org jessie-updates/main amd64 Packages Err http://deb.debian.org jessie/main amd64 Packages 401 Unauthorized Err http://deb.debian.org jessie-updates/main amd64 Packages 401 Unauthorized Err http://security.debian.org jessie/updates/main amd64 Packages Err http://security.debian.org jessie/updates/main amd64 Packages Err http://security.debian.org jessie/updates/main amd64 Packages 401 Unauthorized W: Failed to fetch http://security.debian.org/dists/jessie/updates/main/binary-amd64/Packages 401 Unauthorized

> W: Failed to fetch http://deb.debian.org/debian/dists/jessie/main/binary-amd64/Packages 401 Unauthorized
> 
> W: Failed to fetch http://deb.debian.org/debian/dists/jessie-updates/main/binary-amd64/Packages 401 Unauthorized
> 
> E: Some index files failed to download. They have been ignored, or old ones used instead.

How to create custom as stated above? Thanks in advance.

**Comment by yosifkit** [comment]
That looks like a networking issue.  Can containers get out to the internet or do they need something like an HTTP_PROXY?

If the custom image only removes the `CMD` line what is the use case? You could accomplish the same with a Dockerfile with just two lines: `FROM mariadb:10` and `CMD []`

**Comment by w7089** [comment]
Hi, thanks a lot, u were right. It's related to not using proxy.Thanks. overriding CMD works.The use case is not to launch mysqld process immediately after image is run, but at some point in the future. It's related to running Galera cluster with docker-swarm and to the fact that the first node should be bootstrap node and other 2 are expected to join the cluser. So there are 2 different ways needed to run mysqld. Couldn't come up with other solution than delay mysqld process and run it inside the container later with necessary arguments. Would be happy to hear other suggestions as well.Regards.11.04.2017, 00:33, "yosifkit" <notifications@github.com>:That looks like a networking issue.  Can containers get out to the internet or do they need something like an HTTP_PROXY?
If the custom image only removes the CMD line what is the use case? You could accomplish the same with a Dockerfile with just two lines: FROM mariadb:10 and CMD []
