### ISSUE TITLE
Complains about being started as root

### ISSUE THREAD

**Issue by The-Judge** [docker-library/mariadb#11]
When starting the container, it is being stoped, since mariadb is started as "root", which mariadb doesn't allow:

inished mysql_install_db
150415  9:13:44 [ERROR] Fatal error: Please read "Security" section of the manual to find out how to run mysqld as root!

150415  9:13:44 [ERROR] Aborting

150415  9:13:44 [Note] mysqld: Shutdown complete

**Comment by yosifkit** [comment]
Which version are you using?  Did you override the default config in `/etc/mysql/my.cnf`?  That config contains the user that mariadb will use to step down from root, if it is not there mariadb will be unable to do so.  If you need to provide a custom config, you can place it in `/etc/mysql/conf.d/` and it will be included by the default config.

```console
$ cat /etc/mysql/my.cnf
...
[mysqld]
#
# * Basic Settings
#
user		= mysql
...
!includedir /etc/mysql/conf.d/
```

**Comment by The-Judge** [comment]
Hi yosifkit, thanks for your reply.

Sorry, I made a dumb mistake without noticing. You are right, I did override the default settings without noticing.
So, everything is ok with the image and this can be closed.

Thank you.
