### ISSUE TITLE
There is no tag for version 10.2 and 10.3

### ISSUE THREAD

**Issue by dmelo** [docker-library/mariadb#110]
Although the PR #83 was merged on master branch, there is still no new tags on https://hub.docker.com/_/mariadb/ .

Is there a reason not to publish 10.2?

**Comment by yosifkit** [comment]
> See a change merged here that doesn't show up on the Docker Hub yet? Check the "library/mariadb" manifest file in the docker-library/official-images repo, especially PRs with the "library/mariadb" label on that repo. For more information about the official images process, see the docker-library/official-images readme.
>
> \- https://github.com/docker-library/mariadb/tree/0e47b2c05c05b00c3e1be396f48967d7bc6b6a48#about-this-repo

We should be making a PR to the official images shortly.
