### ISSUE TITLE
Docker hub documentation: "Where to Store Data" options are not clear

### ISSUE THREAD

**Issue by barrystaes** [docker-library/mariadb#120]
The "Where to Store Data" section in the [MariaDB Docker Hub Page](https://hub.docker.com/_/mariadb/) is not very clear to me.

The two mentioned options sound like _the same thing but worded differently_. I guess one of these options intends to describe using a docker volume for persistent data, and the other refers to mounting on host directly.
Also; the two links both are outdated and end up being redirected to https://docs.docker.com/engine/admin/volumes/volumes/

> **Where to Store Data**
> Important note: There are several ways to store data used by applications that run in Docker containers. We encourage users of the mariadb images to familiarize themselves with the options available, including:
> 
> Let Docker manage the storage of your database data [by writing the database files to disk on the host system using its own internal volume management](https://docs.docker.com/engine/tutorials/dockervolumes/#adding-a-data-volume). This is the default and is easy and fairly transparent to the user. The downside is that the files may be hard to locate for tools and applications that run directly on the host system, i.e. outside containers.
> Create a data directory on the host system (outside the container) and [mount this to a directory visible from inside the container](https://docs.docker.com/engine/tutorials/dockervolumes/#mount-a-host-directory-as-a-data-volume). This places the database files in a known location on the host system, and makes it easy for tools and applications on the host system to access the files. The downside is that the user needs to make sure that the directory exists, and that e.g. directory permissions and other security mechanisms on the host system are set up correctly.

**Comment by wglambert** [comment]
By using volumes you get certain docker integrated functionality such as 
> Volumes are easier to back up or migrate than bind mounts.
You can manage volumes using Docker CLI commands or the Docker API.
Volumes work on both Linux and Windows containers.
Volumes can be more safely shared among multiple containers.
Volume drivers allow you to store volumes on remote hosts or cloud providers, to encrypt the contents of volumes, or to add other functionality.
A new volume’s contents can be pre-populated by a container.
https://docs.docker.com/storage/volumes/

In contrast:
>Bind mounts are very performant, but they rely on the host machine’s filesystem having a specific directory structure available.
https://docs.docker.com/storage/bind-mounts/

> When in doubt, the best all-around configuration is to use a modern Linux distribution with a kernel that supports the overlay2 storage driver, and to use Docker volumes for write-heavy workloads instead of relying on writing data to the container’s writable layer.
https://docs.docker.com/storage/storagedriver/select-storage-driver
