### ISSUE TITLE
Use Debian:stretch-slim for newer images

### ISSUE THREAD

**Issue by andrerom** [docker-library/mariadb#121]
While I still think there should be alpine variant of this image (#53), independently of whatever oracle does, the base debain image should be updated to use `debian:stretch-slim`, at the very least for `mariadb:10.3`. As this seems to be the new standard _debian_ base image most new versions of official images use.

**Comment by waja** [comment]
And there is to mention that [LTS Support](https://wiki.debian.org/LTS) for Debian Jessie ends at 31st May 2018.

**Comment by schliflo** [comment]
@waja according to your link support for Wheezy will end 31st May 2018. Jessie isn't even in LTS yet ;) - so that should be fine until 2020

**Comment by waja** [comment]
> @waja according to your link support for Wheezy will end 31st May 2018. Jessie isn't even in LTS yet ;) - so that should be fine until 2020

Oh dear ... since some time I'm messing with Debian code names. Thats way too much to memory since potato. :)

**Comment by colinmollenhour** [comment]
A report on my Galera image project mentions that there is a bug in tail that is fixed in the newer versions so that is one issue that upgrading would fix:

https://github.com/colinmollenhour/mariadb-galera-swarm/issues/33#issuecomment-371396751

**Comment by tianon** [comment]
This was switched to Ubuntu instead in https://github.com/docker-library/mariadb/pull/184 (for better upstream support and thus better multiarch support), and the Ubuntu images are by default already "slim". :+1:
