### ISSUE TITLE
Secret root password

### ISSUE THREAD

**Issue by Fabryprog** [docker-library/mariadb#131]
hello everyone,

Can i use a secret to specify MYSQL_ROOT_PASSWORD? Today i put value only into an enviroment variable!

**Comment by thaJeztah** [comment]
Looks like the same options are available as in [the mysql image](https://hub.docker.com/_/mysql/); 

> ### Docker secrets
> As an alternative to passing sensitive information via environment variables, `_FILE` may be appended to the previously listed environment variables, causing the initialization script to load the values for those variables from files present in the container. In particular, this can be used to load passwords from Docker secrets stored in `/run/secrets/<secret_name>` files. For example:
> 
```bash
$ docker run --name some-mysql -e MYSQL_ROOT_PASSWORD_FILE=/run/secrets/mysql-root -d mysql:tag
```

> Currently, this is only supported for `MYSQL_ROOT_PASSWORD`, `MYSQL_ROOT_HOST`, `MYSQL_DATABASE`, `MYSQL_USER`, and `MYSQL_PASSWORD`.

Code for that feature is in the entrypoint script; https://github.com/docker-library/mariadb/blob/master/10.3/docker-entrypoint.sh#L21-L41


It's not mentioned in the documentation, so perhaps you're interested in opening a pull request to update the documentation with that information?
