### ISSUE TITLE
Enable mysql.sock Unix Socket

### ISSUE THREAD

**Issue by kawaii** [docker-library/mariadb#134]
Hello! I've been using the latest MariaDB Docker image and would like to make use of the Unix socket by mounting it into my application's Docker container so that I can eliminate the TCP overhead. Is this possible in the current image or would some modifications be required? Perhaps it could be implemented as an environment variable?

**Comment by tanji** [comment]
Just mount the `/run/mysqld/` directory, on the other hand you will need proper permissions.

This blog post has relevant explanations: https://www.jujens.eu/posts/en/2017/Feb/15/docker-unix-socket/

**Comment by kawaii** [comment]
Thanks @tanji, worked perfectly.
