### ISSUE TITLE
Add MyRocks

### ISSUE THREAD

**Issue by amq** [docker-library/mariadb#135]
MyRocks engine is one of the highlights of MariaDB 10.2

Compared to InnoDB, it uses less space and is faster for most workloads. It is also optimized for SSD.

https://mariadb.com/kb/en/library/getting-started-with-myrocks/

**Comment by tanji** [comment]
@amq you can do that easily with a simple dockerfile:

```
FROM mariadb:10.2
RUN apt-get update && apt-get -y install mariadb-plugins-rocksdb && rm -rf /var/cache/apt/lists/*
```

Then:

```
docker pull mariadb:10.2
docker build -t myrocks .
docker run -d -p 3306:3306 --name myrocks -e MYSQL_ROOT_PASSWORD=my-secret-pw myrocks
mysql -h 127.0.0.1 -P3306 -u root -pmy-secret-password 
```

Enjoy your MyRocks-enabled MariaDB!

**Comment by tanji** [comment]
Thanks, I've fixed the original posting!

**Comment by qedrakmar** [comment]
This looks resolved.  Closing, and Thanks!

**Comment by emansom** [comment]
Any chance we can get this MyRocks storage engine included by default or an official tag added e.g. `:11.7-myrocks` that ships it?

**Comment by grooverdan** [comment]
I'm still too embarrassed by the lack of updates https://jira.mariadb.org/browse/MDEV-36264 to seriously consider it yet.
