### ISSUE TITLE
MariaDB instance not starting after update

### ISSUE THREAD

**Issue by dmp1ce** [docker-library/mariadb#138]
I am getting the following errors from my log. I only updated the image and restarted. Could a recent change in the image have caused these errors? My host has plenty of space, so I’m not sure why I’m getting the out of space error for `./ibtmp1`

The issue occurs when updating from mariadb 10.2.9 to 10.2.10.

```
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Uses event mutexes
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Compressed tables use zlib 1.2.8
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Using Linux native AIO
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Number of pools: 1
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Using SSE2 crc32 instructions
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Completed initialization of buffer pool
db_1           | 2017-11-07 21:11:32 140191215482624 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
db_1           | 2017-11-07 21:11:32 140191958161280 [Note] InnoDB: Highest supported file format is Barracuda.
db_1           | 2017-11-07 21:11:33 140191958161280 [Note] InnoDB: 128 out of 128 rollback segments are active.
db_1           | 2017-11-07 21:11:33 140191958161280 [Note] InnoDB: Creating shared tablespace for temporary tables
db_1           | 2017-11-07 21:11:33 140191958161280 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
db_1           | 2017-11-07 21:11:33 140191958161280 [ERROR] InnoDB: preallocating 12582912 bytes for file ./ibtmp1 failed with error 22
db_1           | 2017-11-07 21:11:33 140191958161280 [ERROR] InnoDB: Could not set the file size of './ibtmp1'. Probably out of disk space
db_1           | 2017-11-07 21:11:33 140191958161280 [ERROR] InnoDB: Unable to create the shared innodb_temporary
db_1           | 2017-11-07 21:11:33 140191958161280 [ERROR] InnoDB: Plugin initialization aborted with error Generic error
db_1           | 2017-11-07 21:11:38 140191958161280 [Note] InnoDB: Starting shutdown...
db_1           | 2017-11-07 21:11:38 140191958161280 [Note] InnoDB: Removed temporary tablespace data file: "ibtmp1"
db_1           | 2017-11-07 21:11:38 140191958161280 [ERROR] Plugin 'InnoDB' init function returned error.
db_1           | 2017-11-07 21:11:38 140191958161280 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
db_1           | 2017-11-07 21:11:38 140191958161280 [Note] Plugin 'FEEDBACK' is disabled.
db_1           | 2017-11-07 21:11:38 140191958161280 [ERROR] Unknown/unsupported storage engine: InnoDB
db_1           | 2017-11-07 21:11:38 140191958161280 [ERROR] Aborting
```

**Comment by yosifkit** [comment]
Perhaps similar to https://forums.docker.com/t/official-mysql-image-wont-run/1351?  The only difference between the versions is the version: https://github.com/docker-library/mariadb/commit/f50d0a8218602a64806a4eb907b3b5dcc5916981.

**Comment by dmp1ce** [comment]
Error messages are different. The error occurs with `ibtmp1` for me.

Someone on IRC commented that this might be due to a InnoDB version change from MySQL 5.7. I'm not sure if that is helpful information.

**Comment by t3kme** [comment]
Just confirming I have this same issue with mariadb:latest and mariadb:10.2.9 the suggested fix from  @dmp1ce  post here: https://superuser.com/questions/1267663/docker-mariadb-instance-not-starting-after-update. I am going to keep poking around the interwebz.

**Comment by stuckj** [comment]
FYI, I'm seeing the same error. For now I've just downgraded the mariadb container. But...definitely something seems odd with this update.

**Comment by alexhaydock** [comment]
For what it's worth, I'm experiencing this issue too, but only on `mariadb:10.3`.

Downgrading to `mariadb:10.2` solves the issue.

**Comment by vctls** [comment]
I tried downgrading to 10.2, but I still get the error.

**Comment by alexhaydock** [comment]
@vctls From your compose file it looks like you are using a volume, but have switched away from using a bind mount. Is that what you mean fixes the issue?

**Comment by vctls** [comment]
Sorry, you're right, it's the bind mount that's causing the issue.
The `dbsock` volume works fine.
Just tried again on another Windows computer after downgrading to 10.1 (for other compatibility reasons), and it still doesn't work.

**Comment by tianon** [comment]
This was fixed by https://github.com/docker-library/mariadb/pull/168. :+1:
