### ISSUE TITLE
XtraBackup or MariaDB Backup

### ISSUE THREAD

**Issue by Renkas** [docker-library/mariadb#141]
Is there a reason the images contain XtraBackup instead of MariaDB Backup?

We are currently in the process of choosing which to use - MariaDB Backup seems lika a obvious choice but these docker images contain XtraBackup for some reason. Is there a specific reason?

EDIT: I read mariadb (10.2) changelog and it seems MariaDB Backup is added from 10.2.7 onwards and is stable starting from 10.2.10. I'm still using 10.2.6. So I'll update and have a look at it then.

But if it's included and stable in 10.2.10 - isn't the XtraBackup obsolete in these images? Or do you want to keep them for some kind of backwards compatibility?

**Comment by tanji** [comment]
There's a long discussion on this subject in the following PR:
https://github.com/docker-library/mariadb/pull/111

**Comment by w7089** [comment]
i've added
` wsrep_sst_method = mariabackup`
to _[mysqld]_ section in _my.cnf_
as specified [here](https://mariadb.com/kb/en/library/mariadb-backup-overview/#using-mariadb-backup-for-galera-ssts)
and getting errors in mariadb error.log

> WSREP_SST: [ERROR] mariabackup not in path: /usr/sbin:/sbin:/usr//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin (20180318 15:30:45.409)
> 2018-03-18 15:30:45 139657773836032 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_mariabackup --role 'joiner' --address '10.0.0.218' --datadir '/var/lib/mysql/'   --parent '625'  ''
>         Read: '(null)'
> 2018-03-18 15:30:45 139657773836032 [ERROR] WSREP: Process completed with error: wsrep_sst_mariabackup --role 'joiner' --address '10.0.0.218' --datadir '/var/lib/mysql/'   --parent '625'  '' : 2 (No such file or directory)
> 2018-03-18 15:30:45 139658158028544 [ERROR] WSREP: Failed to prepare for 'mariabackup' SST. Unrecoverable.
> 2018-03-18 15:30:45 139658158028544 [ERROR] Aborting
 
Using image with MariaDB 10.2.13.
Is it only possible to use _rsync_ as SST method?

**Comment by tianon** [comment]
Closing in favor of the discussion over in #111 (which has quite a bit more detail).
