### ISSUE TITLE
service mysql restart, fails

### ISSUE THREAD

**Issue by choma** [docker-library/mariadb#151]
I guess this is not a bug, but it's annoying in my case: I need to restart the mariadb server , NOT the container (I'm using mariadb as a base image, so I have other processes running. I know this is not the way docker should be used, but I need it to test something).
Since there is no `debian-sys-main` user in the default install, it is not possible to stop/restart the service:
``` bash
docker pull mariadb:latest
docker run --name mariadb-test -e MYSQL_ROOT_PASSWORD=mypass -d mariadb
docker exec -it mariadb-test bash
root@xxxxxxxx:/$ service mysql stop
[FAIL] Stopping MariaDB database server: mysqld failed!
```
[Here](https://serverfault.com/questions/9948/what-is-the-debian-sys-maint-mysql-user-and-more#9952) are some more details (not docker specific).

I got a couple of questions:
1) is it done like this on purpose (so the container won't die when someone restart mariadb)?
2) if I use the image as intended, how would I make mariadb server apply changes in the config files (since restarting the container doesn't seem to work)?

Anyway, this is what I did, for those whom may find it useful:
``` bash
# get the password for debian-sys-maint
root@xxxxxxxx:/$ thepass=$(awk '/password/ {print $NF}' /etc/mysql/debian.cnf | head -1)
# grant necessary permissions
root@xxxxxxxx:/$ echo "GRANT RELOAD, SHUTDOWN ON *.* TO 'debian-sys-maint'@'localhost' IDENTIFIED BY '$thepass' WITH GRANT OPTION;FLUSH PRIVILEGES;" | mysql -uroot -pmypass
```

**Comment by tanji** [comment]
mariadb runs as PID 1, so restarting the container is equivalent to restarting mariadb.
If you want to apply your config changes just restart the container.

**Comment by choma** [comment]
Yes it works... I just was editing config files in the wrong way.
I'll close the issue. I'm sorry for the noise.
