### ISSUE TITLE
NFS woes as /var/lib/mysql volume

### ISSUE THREAD

**Issue by r3pek** [docker-library/mariadb#153]
This image doesn't support NFS volumes and because of that mariadb fails to start due to no locking support for NFS (which is really usefull to have the DB shared amongst nodes).

This is the error I get:
 InnoDB: Unable to lock ./ibdata1 error: 37

**Comment by yosifkit** [comment]
Are you trying to start multiple mariadb containers pointed at the same directory on NFS?

**Comment by r3pek** [comment]
@yosifkit no, just one.

**Comment by r3pek** [comment]
OK, disregard this issue. Misconfiguration on my part. (was missing rpc-statd daemon on one of the nodes)
