### ISSUE TITLE
MariaBackup as SST method doesn't work

### ISSUE THREAD

**Issue by w7089** [docker-library/mariadb#156]
i've added
` wsrep_sst_method = mariabackup`
to _[mysqld]_ section in _my.cnf_
as specified [here](https://mariadb.com/kb/en/library/mariadb-backup-overview/#using-mariadb-backup-for-galera-ssts)
and getting errors in _mariadb error.log_ while trying to configure cluster and starting _mysqld_

> WSREP_SST: [ERROR] mariabackup not in path: /usr/sbin:/sbin:/usr//bin:/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin (20180318 15:30:45.409)
> 2018-03-18 15:30:45 139657773836032 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_mariabackup --role 'joiner' --address '10.0.0.218' --datadir '/var/lib/mysql/'   --parent '625'  ''
>         Read: '(null)'
> 2018-03-18 15:30:45 139657773836032 [ERROR] WSREP: Process completed with error: wsrep_sst_mariabackup --role 'joiner' --address '10.0.0.218' --datadir '/var/lib/mysql/'   --parent '625'  '' : 2 (No such file or directory)
> 2018-03-18 15:30:45 139658158028544 [ERROR] WSREP: Failed to prepare for 'mariabackup' SST. Unrecoverable.
> 2018-03-18 15:30:45 139658158028544 [ERROR] Aborting
 
Using image with MariaDB 10.2.13.
Is it only possible to use _rsync_ as SST method?

**Comment by grooverdan** [comment]
The maria-backup-10.2 package isn't installed in the container. Discussion per #141 

For sst:

xtrabackup-v2 and probably mysqldump are available.

**Comment by wglambert** [comment]
Closing to redirect discussion to https://github.com/docker-library/mariadb/pull/111, as https://github.com/docker-library/mariadb/issues/141 was also redirected there.
