### ISSUE TITLE
Warning on database initialization: Failed to load slave replication

### ISSUE THREAD

**Issue by strarsis** [docker-library/mariadb#163]
On startup of mariadb container (WSL/Docker for Windows), 
when initializing the database, a warning is logged:
````
[Warning] Failed to load slave replication state from table mysql.gtid_slave_pos: 1146: Table 'mysql.gtid_slave_pos' doesn't exist
````

(New issue, originally stated in https://github.com/docker-library/mariadb/issues/28#issuecomment-385954280.)

**Comment by wglambert** [comment]
https://mariadb.com/kb/en/library/mysqlgtid_slave_pos-table/

Replication is not setup upon startup, so the warning is informing you of that. Since it isn't a bug or error in the image I'm going to close.

**Comment by FrancYescO** [comment]
is there a way to totally disable replication? this is also creating the `multi-master.info` in data folder, but i want to keep data folder read-only

**Comment by grooverdan** [comment]
@FrancYescO  -  please create a new issue with details on how you have configured replication. How are you starting MariaDB?
