### ISSUE TITLE
Warning on startup: 'proxies_priv' entry '@% root@[...]' ignored in --skip-name-resolve mode.

### ISSUE THREAD

**Issue by strarsis** [docker-library/mariadb#164]
On startup of mariadb container (WSL/Docker for Windows) a warning is logged:
````
'proxies_priv' entry '@% root@[...]' ignored in --skip-name-resolve mode.
````

**Comment by wglambert** [comment]
https://bugs.mysql.com/bug.php?id=81441

A warning does not inherently indicate an error with the image, if you encountered anomalous behavior that isn't present in a non-dockerized installation then there could be an issue with the image, but this warning is neither a bug or an issue with the image

**Comment by chiqui3d** [comment]
Hello @wglambert,
I have the same problem, how is it supposed to be fixed?

Thanks

**Comment by grooverdan** [comment]
Like previous, it isn't a problem - ignore it.

**Comment by chiqui3d** [comment]
Thank you for your response @grooverdan. Currently to eliminate the error with skip-name-resolver enabled I have added a simple startup script in the image like the following:

`ADD ./docker/mysql/init.sql /docker-entrypoint-initdb.d/init.sql`

init.sql

`DELETE FROM mysql.proxies_priv WHERE Host != "localhost"`


Once I run the query at the start, I don't get the error anymore. I don't know if it is correct what I am doing. I also don't understand why Mariadb generates a privilege with the name of my container. I don't know if there is a way to tell it not to generate that privilege, or if I don't really understand the logic of this.


Thank you very much.
