### ISSUE TITLE
using xtrabackup instead of rsync as SST

### ISSUE THREAD

**Issue by w7089** [docker-library/mariadb#166]
I have configured mariadb galera cluster as docker swarm service:
during cluster startup rsync (default SST method) works fine.
Wanted to change it to xtrabackup or xtrabackup-v2, so used the following configuration in my.cnf according to [docs]([url](http://galeracluster.com/documentation-webpages/sst.html#id3)):
```
[mysqld]
wsrep_sst_auth = <wsrep_sst_user>:<password>
wsrep_sst_method = wsrep_sst_xtrabackup-v2 (or wsrep_sst_xtrabackup)
datadir = /var/lib/mysql/

[client]
socket =/var/run/mysqld/mysqld.sock
```
and getting the errors below:

> 2018-05-07 12:08:27 140127393273600 [Note] WSREP: Running: 'wsrep_sst_wsrep_sst_xtrabackup-v2 --role 'joiner' --address '10.0.0.29' --datadir '/var/lib/mysql/'   --parent '114'  '' '
> sh: 1: wsrep_sst_wsrep_sst_xtrabackup-v2: not found
> 2018-05-07 12:08:27 140127393273600 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_wsrep_sst_xtrabackup-v2 --role 'joiner' --address '10.0.0.29' --datadir '/var/lib/mysql/'   --parent '114'  ''
>         Read: '(null)'
> 2018-05-07 12:08:27 140127393273600 [ERROR] WSREP: Process completed with error: wsrep_sst_wsrep_sst_xtrabackup-v2 --role 'joiner' --address '10.0.0.29' --datadir '/var/lib/mysql/'   --parent '114'  '' : 2 (No such file or directory)
> 2018-05-07 12:08:27 140127610996480 [ERROR] WSREP: Failed to prepare for 'wsrep_sst_xtrabackup-v2' SST. Unrecoverable.
> 2018-05-07 12:08:27 140127610996480 [ERROR] Aborting

How to configure xtrabackup as SST method correctly with the image?

**Comment by tanji** [comment]
`wsrep_sst_method` is `xtrabackup-v2`, not `wsrep_sst_xtrabackup-v2` ...

By the way, although I'm happy to help, those aren't docker issues, and are better asked for on MariaDB mailing list or forums.

**Comment by w7089** [comment]
i thought it's docker issue, because i use mariadb docker image inside docker swarm service and there's some special xtrabackup configuration related to the fact that ips are virtual, etc.... rsync works without effort, but xtrabackup doesn't and do use galera [docs](http://galeracluster.com/documentation-webpages/sst.html#id3)
sorry if i'm wrong and thanks a lot. i tried to use _xtrabackup-v2_ as u suggested and get the errors below:


> 2018-05-07 13:08:26 139750451541760 [Warning] WSREP: Gap in state sequence. Need state transfer.
> 2018-05-07 13:08:26 139750232831744 [Note] WSREP: Running: 'wsrep_sst_xtrabackup-v2 --role 'joiner' --address '10.0.0.37' --datadir '/var/lib/mysql/'   --parent '108'  '' '
> WSREP_SST: [INFO] Logging all stderr of SST/Innobackupex to syslog (20180507 13:08:26.937)
> 2018-05-07 13:08:29 139750249850624 [Note] WSREP: (fdead878, 'tcp://0.0.0.0:4567') turning message relay requesting off
> 2018-05-07 13:10:07 139750232831744 [ERROR] WSREP: Failed to read 'ready <addr>' from: wsrep_sst_xtrabackup-v2 --role 'joiner' --address '10.0.0.37' --datadir '/var/lib/mysql/'   --parent '108'  ''
>         Read: '(null)'
> 2018-05-07 13:10:07 139750232831744 [ERROR] WSREP: Process completed with error: wsrep_sst_xtrabackup-v2 --role 'joiner' --address '10.0.0.37' --datadir '/var/lib/mysql/'   --parent '108'  '' : 32 (Broken pipe)
> 2018-05-07 13:10:07 139750451541760 [ERROR] WSREP: Failed to prepare for 'xtrabackup-v2' SST. Unrecoverable.
> 2018-05-07 13:10:07 139750451541760 [ERROR] Aborting

> Error in my_thread_global_end(): 1 threads didn't exit

**Comment by w7089** [comment]
Using MariaDB  image with 10.2.14 version helped to resolve the issue. There's a known [bug ](https://jira.mariadb.org/browse/MDEV-15254)with 10.2.13
