### ISSUE TITLE
Query caching should not be enabled by default

### ISSUE THREAD

**Issue by bwaldvogel** [docker-library/mariadb#169]
Query caching is enabled in MariaDB Docker images although it’s not the default behaviour of a vanilla MariaDB server (see the [documentation of `query_cache_type`](https://mariadb.com/kb/en/library/server-system-variables/#query_cache_type)).
This probably happens because `query_cache_size` is set to a non-default value.

It is especially problematic since query caching has a regression in MariaDB 10.2.x and 10.3.x which causes `SELECT` to return wrong results in certain scenarios (see [MDEV-16087](https://jira.mariadb.org/browse/MDEV-16087) for details).

### Steps to reproduce
```
> docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=test -d mariadb:10.2.14
```
```
> mysql -h 127.0.0.1 -u root --password=test -e 'select @@query_cache_type'
+--------------------+
| @@query_cache_type |
+--------------------+
| ON                 |
+--------------------+
```

```
> docker run -p 3306:3306 -e MYSQL_ROOT_PASSWORD=test -d mariadb:10.3.6
```
```
> mysql -h 127.0.0.1 -u root --password=test -e 'select @@query_cache_type'
+--------------------+
| @@query_cache_type |
+--------------------+
| ON                 |
+--------------------+
```

**Comment by yosifkit** [comment]
This is not something we set, but is part of the install from MariaDB apt packages (http://ftp.osuosl.org/pub/mariadb/repo):

```console
$ docker run -it --rm mariadb:10.2.15 bash
root@4ee57f4e20ce:/# grep query_cache /etc/mysql/*.cnf
/etc/mysql/my.cnf:query_cache_limit		= 128K
/etc/mysql/my.cnf:query_cache_size		= 64M
/etc/mysql/my.cnf:#query_cache_type		= DEMAND
```

We just comment out a few values that cause issues in a Docker environment, and then add a couple in a separate `docker.cnf`:

https://github.com/docker-library/mariadb/blob/2027f882cdedee71dcbcf34fd3e3b166306980a8/10.3/Dockerfile#L108-L112

**Comment by bwaldvogel** [comment]
Thanks. Where can I file a bug report for the MariaDB 10.2 and 10.3 apt packages?

**Comment by tianon** [comment]
I think https://jira.mariadb.org/projects/MDEV/issues is probably the
correct place, but I could be wrong.

**Comment by bwaldvogel** [comment]
Thanks, I’ve filed [MDEV-16251](https://jira.mariadb.org/browse/MDEV-16251).
