### ISSUE TITLE
mariadb connect plugin triggers a mariadb server upgrade

### ISSUE THREAD

**Issue by lanm2434** [docker-library/mariadb#172]
I am trying to build an image on top of mariadb:2014 that includes the mariadb-plugin-connect and it upgrades the mariadb to 10.2.15. Our base line at this moment is 10.2.14 and we change our baseline each 3 months and the next change happens in august. If  I do not include the apt-get install for the connect plugin, mariadb remains at 10.2.14. I am joining the Dockerfile used:

FROM mariadb:10.2.14

ENV TZ   Canada/Eastern

# procps is very common in build systems, and is a reasonably small package
RUN apt-get update && apt-get install -y --no-install-recommends \
        curl \
		git \
		mariadb-plugin-connect \
		openssh-client \
		subversion \
		procps \
		unixODBC \
	&& rm -rf /var/lib/apt/lists/*

# UdeS CA
RUN curl --insecure --output /usr/local/share/ca-certificates/udes-ca.crt https://outils.si.sti.usherbrooke.ca/scripts/udesca.pem && update-ca-certificates \
	&& curl https://outils.si.sti.usherbrooke.ca/scripts/udesca.pem > /dev/null

COPY includes/udes.cnf /etc/mysql/conf.d
#COPY includes/ha_connect.so /usr/lib/mysql/plugin

CMD ["mysqld"]

 and here is the output of the build:
Deploying 'udes-mariadb-dev Dockerfile: mariadb-docker/udes-mariadb/Dockerfile'...
Building image...
Step 1/6 : FROM mariadb:10.2.14

 ---> 2cbeee8bd9cf

Step 2/6 : ENV TZ   Canada/Eastern

 ---> Running in 4045076c5512

Removing intermediate container 4045076c5512

 ---> 731f55745229

Step 3/6 : RUN apt-get update && apt-get install -y --no-install-recommends         curl 		git 		mariadb-plugin-connect 		openssh-client 		subversion 		procps 		unixODBC 	&& rm -rf /var/lib/apt/lists/*

 ---> Running in cbe3ded5e229

Get:1 https://repo.percona.com jessie InRelease [15.9 kB]

Get:2 http://security.debian.org jessie/updates InRelease [94.4 kB]
Get:3 http://ftp.osuosl.org jessie InRelease [3222 B]

Get:4 https://repo.percona.com jessie/main amd64 Packages [21.1 kB]

Ign http://deb.debian.org jessie InRelease

Get:5 http://security.debian.org jessie/updates/main amd64 Packages [623 kB]

Get:6 http://deb.debian.org jessie-updates InRelease [145 kB]

Get:7 http://deb.debian.org jessie Release.gpg [2434 B]

Get:8 http://deb.debian.org jessie Release [148 kB]

Get:9 http://ftp.osuosl.org jessie/main amd64 Packages [7512 B]

Get:10 http://deb.debian.org jessie-updates/main amd64 Packages [23.0 kB]

Get:11 http://deb.debian.org jessie/main amd64 Packages [9064 kB]

Fetched 10.1 MB in 6s (1591 kB/s)
Reading package lists...

Reading package lists...

Building dependency tree...

Reading state information...

The following extra packages will be installed:
  git-man libapr1 libaprutil1 libbsd0 libcurl3 libedit2 liberror-perl
  libexpat1 libltdl7 libodbc1 libserf-1-1 libsqlite3-0 libsvn1 libxml2
  mariadb-client-10.2 mariadb-client-core-10.2 mariadb-common mariadb-server
  mariadb-server-10.2 mariadb-server-core-10.2 odbcinst odbcinst1debian2

Suggested packages:
  gettext-base git-daemon-run git-daemon-sysvinit git-doc git-el git-email
  git-gui gitk gitweb git-arch git-cvs git-mediawiki git-svn libmyodbc
  odbc-postgresql tdsodbc unixodbc-bin mailx mariadb-test netcat-openbsd
  tinyca ssh-askpass libpam-ssh keychain monkeysphere subversion-tools
  db5.3-util
Recommended packages:
  patch less ssh-client xml-core xauth

The following NEW packages will be installed:
  curl git git-man libapr1 libaprutil1 libbsd0 libedit2 liberror-perl
  libexpat1 libltdl7 libodbc1 libserf-1-1 libsqlite3-0 libsvn1 libxml2
  mariadb-plugin-connect odbcinst odbcinst1debian2 openssh-client subversion
  unixodbc

The following packages will be upgraded:
  libcurl3 mariadb-client-10.2 mariadb-client-core-10.2 mariadb-common
  mariadb-server mariadb-server-10.2 mariadb-server-core-10.2 procps

8 upgraded, 21 newly installed, 0 to remove and 6 not upgraded.
Need to get 22.2 MB of archives.
After this operation, 45.3 MB of additional disk space will be used.
Get:1 http://security.debian.org/debian-security/ jessie/updates/main libxml2 amd64 2.9.1+dfsg1-5+deb8u6 [802 kB]
Get:2 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/ jessie/main mariadb-common all 10.2.15+maria~jessie [3406 B]
Get:3 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/ jessie/main mariadb-server all 10.2.15+maria~jessie [3022 B]

Get:4 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/ jessie/main mariadb-client-core-10.2 amd64 10.2.15+maria~jessie [746 kB]

Get:5 http://deb.debian.org/debian/ jessie/main libbsd0 amd64 0.7.0-2 [67.9 kB]

Get:6 http://deb.debian.org/debian/ jessie/main libedit2 amd64 3.1-20140620-2 [85.1 kB]

Get:7 http://deb.debian.org/debian/ jessie/main libsqlite3-0 amd64 3.8.7.1-1+deb8u2 [438 kB]

Get:8 http://deb.debian.org/debian/ jessie/main libapr1 amd64 1.5.1-3 [95.3 kB]

Get:9 http://deb.debian.org/debian/ jessie/main libexpat1 amd64 2.1.0-6+deb8u4 [80.2 kB]

Get:10 http://deb.debian.org/debian/ jessie/main libaprutil1 amd64 1.5.4-1 [86.2 kB]
Get:11 http://security.debian.org/debian-security/ jessie/updates/main libcurl3 amd64 7.38.0-4+deb8u11 [260 kB]

Get:12 http://deb.debian.org/debian/ jessie/main libltdl7 amd64 2.4.2-1.11+b1 [45.4 kB]

Get:13 http://deb.debian.org/debian/ jessie/main libodbc1 amd64 2.3.1-3 [206 kB]

Get:14 http://deb.debian.org/debian/ jessie/main libserf-1-1 amd64 1.3.8-1 [52.8 kB]

Get:15 http://deb.debian.org/debian/ jessie/main libsvn1 amd64 1.8.10-6+deb8u5 [1075 kB]

Get:16 http://security.debian.org/debian-security/ jessie/updates/main procps amd64 2:3.3.9-9+deb8u1 [236 kB]

Get:17 http://security.debian.org/debian-security/ jessie/updates/main curl amd64 7.38.0-4+deb8u11 [201 kB]

Get:18 http://deb.debian.org/debian/ jessie/main odbcinst amd64 2.3.1-3 [41.9 kB]

Get:19 http://deb.debian.org/debian/ jessie/main odbcinst1debian2 amd64 2.3.1-3 [72.6 kB]

Get:20 http://deb.debian.org/debian/ jessie/main openssh-client amd64 1:6.7p1-5+deb8u4 [693 kB]

Get:21 http://deb.debian.org/debian/ jessie/main liberror-perl all 0.17-1.1 [22.4 kB]

Get:22 http://deb.debian.org/debian/ jessie/main git-man all 1:2.1.4-2.1+deb8u5 [1268 kB]

Get:23 http://deb.debian.org/debian/ jessie/main git amd64 1:2.1.4-2.1+deb8u5 [3694 kB]

Get:24 http://deb.debian.org/debian/ jessie/main unixodbc amd64 2.3.1-3 [51.9 kB]

Get:25 http://deb.debian.org/debian/ jessie/main subversion amd64 1.8.10-6+deb8u5 [923 kB]

Get:26 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/ jessie/main mariadb-server-10.2 amd64 10.2.15+maria~jessie [3765 kB]

Get:27 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/ jessie/main mariadb-client-10.2 amd64 10.2.15+maria~jessie [1103 kB]

Get:28 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/ jessie/main mariadb-server-core-10.2 amd64 10.2.15+maria~jessie [5554 kB]

Get:29 http://ftp.osuosl.org/pub/mariadb/repo/10.2/debian/ jessie/main mariadb-plugin-connect amd64 10.2.15+maria~jessie [492 kB]

debconf: delaying package configuration, since apt-utils is not installed

Fetched 22.2 MB in 21s (1028 kB/s)

Selecting previously unselected package libbsd0:amd64.
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 10856 files and directories currently installed.)

Preparing to unpack .../libbsd0_0.7.0-2_amd64.deb ...

Unpacking libbsd0:amd64 (0.7.0-2) ...

Selecting previously unselected package libedit2:amd64.

Preparing to unpack .../libedit2_3.1-20140620-2_amd64.deb ...

Unpacking libedit2:amd64 (3.1-20140620-2) ...

Selecting previously unselected package libsqlite3-0:amd64.

Preparing to unpack .../libsqlite3-0_3.8.7.1-1+deb8u2_amd64.deb ...

Unpacking libsqlite3-0:amd64 (3.8.7.1-1+deb8u2) ...

Selecting previously unselected package libxml2:amd64.

Preparing to unpack .../libxml2_2.9.1+dfsg1-5+deb8u6_amd64.deb ...

Unpacking libxml2:amd64 (2.9.1+dfsg1-5+deb8u6) ...

Selecting previously unselected package libapr1:amd64.

Preparing to unpack .../libapr1_1.5.1-3_amd64.deb ...

Unpacking libapr1:amd64 (1.5.1-3) ...

Selecting previously unselected package libexpat1:amd64.

Preparing to unpack .../libexpat1_2.1.0-6+deb8u4_amd64.deb ...

Unpacking libexpat1:amd64 (2.1.0-6+deb8u4) ...

Selecting previously unselected package libaprutil1:amd64.
Preparing to unpack .../libaprutil1_1.5.4-1_amd64.deb ...

Unpacking libaprutil1:amd64 (1.5.4-1) ...

Preparing to unpack .../libcurl3_7.38.0-4+deb8u11_amd64.deb ...

Unpacking libcurl3:amd64 (7.38.0-4+deb8u11) over (7.38.0-4+deb8u10) ...

Selecting previously unselected package libltdl7:amd64.
Preparing to unpack .../libltdl7_2.4.2-1.11+b1_amd64.deb ...

Unpacking libltdl7:amd64 (2.4.2-1.11+b1) ...

Selecting previously unselected package libodbc1:amd64.

Preparing to unpack .../libodbc1_2.3.1-3_amd64.deb ...

Unpacking libodbc1:amd64 (2.3.1-3) ...

Selecting previously unselected package libserf-1-1:amd64.
Preparing to unpack .../libserf-1-1_1.3.8-1_amd64.deb ...

Unpacking libserf-1-1:amd64 (1.3.8-1) ...

Selecting previously unselected package libsvn1:amd64.

Preparing to unpack .../libsvn1_1.8.10-6+deb8u5_amd64.deb ...

Unpacking libsvn1:amd64 (1.8.10-6+deb8u5) ...

Preparing to unpack .../mariadb-common_10.2.15+maria~jessie_all.deb ...

Unpacking mariadb-common (10.2.15+maria~jessie) over (10.2.14+maria~jessie) ...

Preparing to unpack .../mariadb-server_10.2.15+maria~jessie_all.deb ...

Unpacking mariadb-server (10.2.15+maria~jessie) over (10.2.14+maria~jessie) ...

Preparing to unpack .../mariadb-client-core-10.2_10.2.15+maria~jessie_amd64.deb ...

Unpacking mariadb-client-core-10.2 (10.2.15+maria~jessie) over (10.2.14+maria~jessie) ...

Setting up mariadb-common (10.2.15+maria~jessie) ...

(Reading database ... 
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 10991 files and directories currently installed.)

Preparing to unpack .../mariadb-server-10.2_10.2.15+maria~jessie_amd64.deb ...

debconf: unable to initialize frontend: Dialog

debconf: (TERM is not set, so the dialog frontend is not usable.)

debconf: falling back to frontend: Readline

invoke-rc.d: policy-rc.d denied execution of stop.

debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Unpacking mariadb-server-10.2 (10.2.15+maria~jessie) over (10.2.14+maria~jessie) ...

debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)
debconf: falling back to frontend: Readline

Preparing to unpack .../mariadb-client-10.2_10.2.15+maria~jessie_amd64.deb ...

Unpacking mariadb-client-10.2 (10.2.15+maria~jessie) over (10.2.14+maria~jessie) ...

Preparing to unpack .../mariadb-server-core-10.2_10.2.15+maria~jessie_amd64.deb ...

Unpacking mariadb-server-core-10.2 (10.2.15+maria~jessie) over (10.2.14+maria~jessie) ...

Selecting previously unselected package odbcinst.
Preparing to unpack .../odbcinst_2.3.1-3_amd64.deb ...

Unpacking odbcinst (2.3.1-3) ...

Selecting previously unselected package odbcinst1debian2:amd64.

Preparing to unpack .../odbcinst1debian2_2.3.1-3_amd64.deb ...

Unpacking odbcinst1debian2:amd64 (2.3.1-3) ...

Preparing to unpack .../procps_2%3a3.3.9-9+deb8u1_amd64.deb ...

invoke-rc.d: policy-rc.d denied execution of stop.

Unpacking procps (2:3.3.9-9+deb8u1) over (2:3.3.9-9) ...

Processing triggers for systemd (215-17+deb8u7) ...

Setting up procps (2:3.3.9-9+deb8u1) ...

invoke-rc.d: policy-rc.d denied execution of start.

Selecting previously unselected package openssh-client.

(Reading database ... 
(Reading database ... 5%
(Reading database ... 10%
(Reading database ... 15%
(Reading database ... 20%
(Reading database ... 40%
(Reading database ... 45%
(Reading database ... 60%
(Reading database ... 65%
(Reading database ... 70%
(Reading database ... 75%
(Reading database ... 80%
(Reading database ... 85%
(Reading database ... 90%
(Reading database ... 95%
(Reading database ... 100%
(Reading database ... 
11023 files and directories currently installed.)

Preparing to unpack .../openssh-client_1%3a6.7p1-5+deb8u4_amd64.deb ...

Unpacking openssh-client (1:6.7p1-5+deb8u4) ...

Selecting previously unselected package curl.

Preparing to unpack .../curl_7.38.0-4+deb8u11_amd64.deb ...

Unpacking curl (7.38.0-4+deb8u11) ...

Selecting previously unselected package liberror-perl.

Preparing to unpack .../liberror-perl_0.17-1.1_all.deb ...

Unpacking liberror-perl (0.17-1.1) ...

Selecting previously unselected package git-man.

Preparing to unpack .../git-man_1%3a2.1.4-2.1+deb8u5_all.deb ...

Unpacking git-man (1:2.1.4-2.1+deb8u5) ...

Selecting previously unselected package git.

Preparing to unpack .../git_1%3a2.1.4-2.1+deb8u5_amd64.deb ...

Unpacking git (1:2.1.4-2.1+deb8u5) ...

Selecting previously unselected package unixodbc.

Preparing to unpack .../unixodbc_2.3.1-3_amd64.deb ...

Unpacking unixodbc (2.3.1-3) ...

Selecting previously unselected package mariadb-plugin-connect.

Preparing to unpack .../mariadb-plugin-connect_10.2.15+maria~jessie_amd64.deb ...

Unpacking mariadb-plugin-connect (10.2.15+maria~jessie) ...

Selecting previously unselected package subversion.
Preparing to unpack .../subversion_1.8.10-6+deb8u5_amd64.deb ...

Unpacking subversion (1.8.10-6+deb8u5) ...

Setting up libbsd0:amd64 (0.7.0-2) ...

Setting up libedit2:amd64 (3.1-20140620-2) ...

Setting up libsqlite3-0:amd64 (3.8.7.1-1+deb8u2) ...

Setting up libxml2:amd64 (2.9.1+dfsg1-5+deb8u6) ...

Setting up libapr1:amd64 (1.5.1-3) ...

Setting up libexpat1:amd64 (2.1.0-6+deb8u4) ...

Setting up libaprutil1:amd64 (1.5.4-1) ...

Setting up libcurl3:amd64 (7.38.0-4+deb8u11) ...

Setting up libltdl7:amd64 (2.4.2-1.11+b1) ...

Setting up libodbc1:amd64 (2.3.1-3) ...

Setting up libserf-1-1:amd64 (1.3.8-1) ...

Setting up libsvn1:amd64 (1.8.10-6+deb8u5) ...

Setting up mariadb-client-core-10.2 (10.2.15+maria~jessie) ...

Setting up mariadb-client-10.2 (10.2.15+maria~jessie) ...

Setting up mariadb-server-core-10.2 (10.2.15+maria~jessie) ...

Setting up mariadb-server-10.2 (10.2.15+maria~jessie) ...

debconf: unable to initialize frontend: Dialog
debconf: (TERM is not set, so the dialog frontend is not usable.)

debconf: falling back to frontend: Readline

invoke-rc.d: policy-rc.d denied execution of stop.

invoke-rc.d: policy-rc.d denied execution of start.

Setting up mariadb-server (10.2.15+maria~jessie) ...

Setting up openssh-client (1:6.7p1-5+deb8u4) ...

Setting up curl (7.38.0-4+deb8u11) ...

Setting up liberror-perl (0.17-1.1) ...

Setting up git-man (1:2.1.4-2.1+deb8u5) ...

Setting up git (1:2.1.4-2.1+deb8u5) ...

Setting up subversion (1.8.10-6+deb8u5) ...

Setting up odbcinst1debian2:amd64 (2.3.1-3) ...

Setting up unixodbc (2.3.1-3) ...

Setting up mariadb-plugin-connect (10.2.15+maria~jessie) ...

Setting up odbcinst (2.3.1-3) ...

Processing triggers for libc-bin (2.19-18+deb8u10) ...

Removing intermediate container cbe3ded5e229

 ---> e84a5dd38c7d

Step 4/6 : RUN curl --insecure --output /usr/local/share/ca-certificates/udes-ca.crt https://outils.si.sti.usherbrooke.ca/scripts/udesca.pem && update-ca-certificates 	&& curl https://outils.si.sti.usherbrooke.ca/scripts/udesca.pem > /dev/null

 ---> Running in 0313c3404856

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1874  100  1874    0     0  41826      0 --:--:-- --:--:-- --:--:-- 42590

Updating certificates in /etc/ssl/certs... 
1 added, 0 removed; done.
Running hooks in /etc/ca-certificates/update.d....
done.

  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
100  1874  100  1874    0     0   119k      0 --:--:-- --:--:-- --:--:--  122k

Removing intermediate container 0313c3404856

 ---> 59fa782edacb

Step 5/6 : COPY includes/udes.cnf /etc/mysql/conf.d

 ---> 47206f190d9e

Step 6/6 : CMD ["mysqld"]

 ---> Running in 1f13f1419ba9

Removing intermediate container 1f13f1419ba9

 ---> 52ff5d293be8

Successfully built 52ff5d293be8

Successfully tagged udes-mariadb-dev:10.2.14

Creating container...
Container Id: a5ee0c36c0537b3123ac884c628b576962f58ea9ea78086b28dcd00567d93b87
Container name: 'udes-mariadb-dev'
Attaching to container 'udes-mariadb-dev'...
Starting container 'udes-mariadb-dev'
'udes-mariadb-dev Dockerfile: mariadb-docker/udes-mariadb/Dockerfile' has been deployed successfully.

**Comment by lanm2434** [comment]
I have uploaded a text of the Dockerfile as the text pasted does not reflect original content.
[Dockerfile.txt](https://github.com/docker-library/mariadb/files/2045923/Dockerfile.txt)

**Comment by lanm2434** [comment]
I managed to understand thta it is the normal behaviour as 10.2.15 is now the 10.2 stable version. I also found out how to install a specific versionwith apt using package=version but version 10.2.14 of the mariadb-plugin-connect cannot be found. Where can I find it?

**Comment by yosifkit** [comment]
Older packages are not available in the MariaDb provided repos :cry:, so I don't think there is a place to find them. The images on Docker Hub were updated to have `10.2.15`; see https://github.com/docker-library/official-images/pull/4367.
