### ISSUE TITLE
Can't connect to database

### ISSUE THREAD

**Issue by IsidoreIsou** [docker-library/mariadb#178]
Hello,

I am trying to set up 2 docker instances : Nextcloud + Mariadb.
I have installed Nextcloud with SQLite default option. But when I want to migrate to use Mariadb, I only got errors. Please see the screenshot attached. 
I am learning this, and I don't know what to do.

Thanks !!

![db migrate](https://user-images.githubusercontent.com/16151406/41786054-b9f7e8f2-7644-11e8-8e60-52a74b4716cc.png)

**Comment by wglambert** [comment]
For your containers to see eachother they have to be either `--link`ed or on the same network; such as `docker network create net -d bridge` and then `docker run --network=net`
And for the addresses you can use to resolve the containers: container IP, hostname, container ID/name

See https://github.com/docker-library/mongo/issues/267#issuecomment-385463382

**Comment by IsidoreIsou** [comment]
Thanks a lot for you help, 
The solution was to use **db** (the service name of my MariaDB container) as hostname !
