### ISSUE TITLE
[Question] Data Directory Mount?

### ISSUE THREAD

**Issue by qops1981** [docker-library/mariadb#2]
Can I mount a Host Directory Path the the Data Directory path for the MariaDB Database? That Way I can Upgrade or Replace the MariaDB Container at will with out loosing database data?

Thanks,
-Bill

**Comment by tianon** [comment]
https://github.com/docker-library/mariadb/blob/cbcee5a22e2be955f6597486465465ed82185698/10.0/Dockerfile#L32

**Comment by yosifkit** [comment]
Yes that would be valid (in your `docker run` just add `-v host/path:/var/lib/mysql`. Which is why we have [this line](https://github.com/docker-library/mariadb/blob/master/5.5/docker-entrypoint.sh#L41) in the entrypoint to ensure the files are writable by the mysql user.

**Comment by qops1981** [comment]
Awesome thanks :D super Helpful!
