### ISSUE TITLE
10.1: mkdir: cannot create directory `': 

### ISSUE THREAD

**Issue by andrerom** [docker-library/mariadb#20]
Tried to use 10.1, and got the following on setup that works with latests:
```
Running mysql_install_db ...
mkdir: cannot create directory `': No such file or directory
Fatal error Can't create database directory ''

The latest information about mysql_install_db is available at
https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
```

**Comment by yosifkit** [comment]
Since the 10.1 series is a [beta](https://mariadb.com/kb/en/mariadb/what-is-mariadb-101/) release, we actually removed building and supporting it in #7.  We unfortunately have no way to remove tags from the Docker Hub.

**Comment by andrerom** [comment]
ok that explains several things, pity you can not hide those.

**Comment by yosifkit** [comment]
Yeah, I would just go off of the "Supported Tags and Dockerfiles" [list](https://hub.docker.com/_/mariadb/#supported-tags-and-respective-dockerfile-links) on every official image, rather than the tags page.
