### ISSUE TITLE
Version 10.2 Fails to Build

### ISSUE THREAD

**Issue by robbmj** [docker-library/mariadb#202]
Hello,

The Dockerfile for 10.2.17 fails to build with the following error

```
The command '/bin/sh -c set -ex; 	export GNUPGHOME="$(mktemp -d)"; 	for key in $GPG_KEYS; do 		gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; 	done; 	gpg --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mariadb.gpg; 	command -v gpgconf > /dev/null && gpgconf --kill all || :; 	rm -r "$GNUPGHOME"; 	apt-key list' returned a non-zero code: 2
```

Steps to reporduce
```
git clone https://github.com/docker-library/mariadb.git
cd mariadb/10.2
docker build .
```

Docker Version:
```
Docker version 17.05.0-ce, build 89658be
```

**Comment by wglambert** [comment]
https://github.com/docker-library/official-images/issues/4252#issuecomment-381783035
>TLDR; GPG servers are extremely flaky . . .

This is what we do for GPG issues https://github.com/docker-library/official-images/issues/4252#issuecomment-405749749

**Comment by tianon** [comment]
See https://travis-ci.org/docker-library/mariadb/jobs/426140925 and https://doi-janky.infosiftr.net/job/multiarch/job/amd64/job/mariadb/lastSuccessfulBuild/console for where this is building successfully.
