### ISSUE TITLE
Please build cross architecture images

### ISSUE THREAD

**Issue by aidan-plenert-macdonald** [docker-library/mariadb#204]
You only build for a couple architectures,

```
$ docker run --rm mplatform/mquery mariadb
Image: mariadb
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm64/v8
   - linux/ppc64le

$ docker run --rm mplatform/mquery ubuntu
Image: ubuntu
 * Manifest List: Yes
 * Supported platforms:
   - linux/amd64
   - linux/arm/v7
   - linux/arm64/v8
   - linux/386
   - linux/ppc64le
   - linux/s390x
```

You can setup cross platform builds like [here](https://lobradov.github.io/Building-docker-multiarch-images/).

**Comment by tianon** [comment]
We can only build for architectures that MariaDB supports and provides binaries for, which is the reason for our current supported architectures list.
