### ISSUE TITLE
Dockerfile 10.3

### ISSUE THREAD

**Issue by freehussain** [docker-library/mariadb#209]
failed to run

+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.ZvzCRwUAQr
+ gpg --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4
gpg: keybox '/tmp/tmp.ZvzCRwUAQr/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address

you have to update gpg key, what is the right one?

**Comment by tianon** [comment]
See https://github.com/docker-library/official-images/issues/4252.
