### ISSUE TITLE
Add ENV flag to install MariaDB galera

### ISSUE THREAD

**Issue by klausenbusk** [docker-library/mariadb#22]
This could be really nice, also I don't need to maintain a fork which just change 1 line.

**Comment by md5** [comment]
@klausenbusk What does your fork look like? Is it not possible to use a derived image (i.e. `FROM mariadb`) instead of forking?

**Comment by klausenbusk** [comment]
> Is it not possible to use a derived image (i.e. FROM mariadb) instead of forking?

Tried that yesterday, must have done something wrong. Could I create a PR for a mariadb-galera Dockerfile? or don't Docker want to support it as a official image?

**Comment by yosifkit** [comment]
I think it would be great to have a Galera Dockerfile; would it work to be `FROM mariadb:version`? Maybe stick in one for each version so we would have `5.5/galera/Dockerfile` and `10.0/galera/Dockerfile`.  We can then tag them with the variant like, `mariadb:10.0-galera`.

**Comment by klausenbusk** [comment]
> I think it would be great to have a Galera Dockerfile; would it work to be FROM mariadb:version? Maybe stick in one for each version so we would have 5.5/galera/Dockerfile and 10.0/galera/Dockerfile. We can then tag them with the variant like, mariadb:10.0-galera.

I have uploaded my derived image here: http://188.228.31.139/dl/mariadb-galera.zip
I start it like (from CoreOS with fleet):
```
docker run --name mariadb-galera --rm=true -p 3306:3306 -p ${COREOS_PRIVATE_IPV4}:4444:4444 -p ${COREOS_PRIVATE_IPV4}:4567:4567 --dns 172.17.42.1 -v /var/lib/mysql:/var/lib/mysql -e NODE_IP=${COREOS_PRIVATE_IPV4} -e CLUSTER_ADDRESS=gcomm://mysql.skydns.local,mysql.skydns.local klausenbusk/mariadb-galera```
For initialize run I just added `--wsrep_cluster_address`.
I fixed PR #23 in run.sh and removed `mysql_tzinfo_to_sql`, also I set `MYSQL_ALLOW_EMPTY_PASSWORD` if `CLUSTER_ADDRESS` env is set, as it will get user list from the cluster. Also `NODE_IP` env need to be set, else it "announce" the internal docker ip, which don't work across nodes.

Take a look! :)

**Comment by macropin** [comment]
FWIW this is our derived image https://github.com/panubo/docker-mariadb-galera

**Comment by yosifkit** [comment]
I believe tanji had a working setup with this compose file: https://github.com/docker-library/mariadb/pull/57#issuecomment-226739810.

**Comment by jpratt3000** [comment]
i am trying to find out if there is support for galera in the current docker or not, can someone let me know please?

**Comment by klausenbusk** [comment]
MariaDB 10.1 include Glaera support. I'm using it in production and it is working fine, you just need the right parameters.

**Comment by stuartz-VernonCo** [comment]
@jpratt3000 We were running Mariadb galera in containers on a WAN locally and on AWS for about 2 years.  You can checkout https://github.com/stuartz/mariadb-cluster.git to get hints for setup.  We used Weave for a secure network for galera to communicate on.
As of July, we no longer had a need for it, so it will not be kept up to the latest and tested.  Feel free to fork it.

**Comment by klausenbusk** [comment]
Lets close this. Galera support is included in MariaDB since 10.1

**Comment by macropin** [comment]
@klausenbusk Where's the documentation on Galera support?

**Comment by klausenbusk** [comment]
> @klausenbusk Where's the documentation on Galera support?

Oh yeh, the documentation is missing.
https://github.com/docker-library/mariadb/pull/24#issuecomment-175784967 contain a example, I do something similar in production, with the notably difference that I override the entrypoint entirely instead of skipping it (`["sh", "-c", "chown -R mysql:mysql /var/lib/mysql && exec gosu mysql mysqld"]`). Feel free to ask any question.

http://mariadb.com, http://percona.com and http://galeracluster.com/ is also worth a look, they contain a lot of documentation.

**Comment by jan-hudec** [comment]
@klausenbusk,

> Lets close this. Galera support is included in MariaDB since 10.1

Hm, I am rather confused. There is a `galera-3` package in their repository that adds an extra library that is supposed to be used as the wsrep-provider. And I couldn't find much documentation regarding whether it is needed or what it is supposed to add.

**Comment by klausenbusk** [comment]
> There is a galera-3 package in their repository that adds an extra library that is supposed to be used as the wsrep-provider.

`galera-3` is required by `mariadb` and should be installed automatic (I suppose). In other word, Galera support should work out-of-box in 10.1+

**Comment by jan-hudec** [comment]
@klausenbusk, not sure why I had the impression the library wasn't there, but checking again it indeed is. Thank you.
