### ISSUE TITLE
Import sql files in parallel

### ISSUE THREAD

**Issue by iBobik** [docker-library/mariadb#224]
Currently all files in /docker-entrypoint-initdb.d are imported one by one in one thread.

Will be nice to increase speed by having option to import them parallelly.

**Comment by yosifkit** [comment]
That is on purpose, most users have imports that are dependent on one another.

> Files will be executed in alphabetical order.
>
> \- [hub docs](https://github.com/docker-library/docs/tree/4981782b64728e66926b349ba0481661bea307a7/mariadb#initializing-a-fresh-instance)

You could just make a shell script that uses ` xargs -n1 -P[num] ` to run a bunch of other sql or sh scripts from a subdirectory. :eyes:
