### ISSUE TITLE
Can't build !!

### ISSUE THREAD

**Issue by smarttang** [docker-library/mariadb#234]
➜  mysql git:(master) ✗ docker build -t smarttang/mysql .
Sending build context to Docker daemon  14.85kB
Step 1/19 : FROM ubuntu:bionic
 ---> 47b19964fb50
Step 2/19 : RUN groupadd -r mysql && useradd -r -g mysql mysql
 ---> Using cache
 ---> 1ee65c00b5ad
Step 3/19 : RUN set -ex; 	apt-get update; 	if ! which gpg; then 		apt-get install -y --no-install-recommends gnupg; 	fi; 	if ! gpg --version | grep -q '^gpg (GnuPG) 1\.'; then 		 apt-get install -y --no-install-recommends dirmngr; 	fi; 	rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> bdec0938d086
Step 4/19 : ENV GOSU_VERSION 1.10
 ---> Using cache
 ---> eb954093a884
Step 5/19 : RUN set -ex; 		fetchDeps=' 		ca-certificates 		wget 	'; 	apt-get update; 	apt-get install -y --no-install-recommends $fetchDeps; 	rm -rf /var/lib/apt/lists/*; 		dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')"; 	wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch"; 	wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc"; 		export GNUPGHOME="$(mktemp -d)"; 	gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4; 	gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu; 	command -v gpgconf > /dev/null && gpgconf --kill all || :; 	rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc; 		chmod +x /usr/local/bin/gosu; 	gosu nobody true; 		apt-get purge -y --auto-remove $fetchDeps
 ---> Using cache
 ---> 9ede5d3d1082
Step 6/19 : RUN mkdir /docker-entrypoint-initdb.d
 ---> Using cache
 ---> 029b08c98473
Step 7/19 : RUN apt-get update && apt-get install -y --no-install-recommends 		apt-transport-https ca-certificates 		pwgen 		tzdata 	&& rm -rf /var/lib/apt/lists/*
 ---> Using cache
 ---> 2e7ed5a0d675
Step 8/19 : ENV GPG_KEYS 	199369E5404BD5FC7D2FE43BCBCB082A1BB943DB 	177F4010FE56CA3336300305F1656F24C74CD1D8 	430BDF5C56E7C94E848EE60C1C4CBDCDCD2EFD2A 	4D1BB29D63D98E422B2113B19334A25F8507EFA5
 ---> Using cache
 ---> 068ce1025cb6
Step 9/19 : RUN set -ex; 	export GNUPGHOME="$(mktemp -d)"; 	for key in $GPG_KEYS; do 		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; 	done; 	gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mariadb.gpg; 	command -v gpgconf > /dev/null && gpgconf --kill all || :; 	rm -r "$GNUPGHOME"; 	apt-key list
 ---> Running in c879a7252bf3
+ mktemp -d
+ export GNUPGHOME=/tmp/tmp.KB4sCSZ23N
+ gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys 199369E5404BD5FC7D2FE43BCBCB082A1BB943DB
gpg: keybox '/tmp/tmp.KB4sCSZ23N/pubring.kbx' created
gpg: keyserver receive failed: Cannot assign requested address
The command '/bin/sh -c set -ex; 	export GNUPGHOME="$(mktemp -d)"; 	for key in $GPG_KEYS; do 		gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys "$key"; 	done; 	gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mariadb.gpg; 	command -v gpgconf > /dev/null && gpgconf --kill all || :; 	rm -r "$GNUPGHOME"; 	apt-key list' returned a non-zero code: 2
➜  mysql git:(master) ✗

**Comment by tianon** [comment]
https://github.com/docker-library/faq/blob/master/README.md#openpgp--gnupg-keys-and-verification
