### ISSUE TITLE
Allow the container to only initialize the /var/lib/mysql folder

### ISSUE THREAD

**Issue by calind** [docker-library/mariadb#243]
Recently, Percona images provie an environment variable `MYSQL_INIT_ONLY`, which if set, just initialize the /var/lib/mysql folder.

See https://github.com/percona/percona-docker/commit/d21dfdbeee5dfd297bd3c46e67c6ab11d0df3141

This is usefull in order to be able to use the container as Kubernetes init container.

**Comment by yosifkit** [comment]
See related comment (and linked issues) for when this was added to official images: https://github.com/docker-library/official-images/pull/5871#issuecomment-490277321

> other SQL images [...] would be unlikely to add this variable
