### ISSUE TITLE
Problem building mariadb 10.2.24 -  returned a non-zero code: 100 

### ISSUE THREAD

**Issue by dnomar** [docker-library/mariadb#250]
I have problems when build mariadb v10.2.24 with the github's Dockerfile, i don´t understand why it is happenning, because i follow all the recomendations from github regarding the package. this is my code who generates the error:

<details>
<code>

> root@sli-wms:/server# docker-compose build 
> Building mariadb
> Step 1/18 : FROM ubuntu:bionic
>  ---> 7698f282e524
> Step 2/18 : RUN groupadd -r mysql && useradd -r -g mysql mysql
>  ---> Using cache
>  ---> 5b8271da7585
> Step 3/18 : RUN set -ex;        apt-get update;         if ! which gpg; then            apt-get install -y --no-install-recommends gnupg;       fi;     if ! gpg --version | grep -q '^gpg (GnuPG) 1\.'; then                 apt-get install -y --no-install-recommends dirmngr;    fi;     rm -rf /var/lib/apt/lists/*
>  ---> Using cache
>  ---> f53d200606a8
> Step 4/18 : ENV GOSU_VERSION 1.10
>  ---> Using cache
>  ---> a14385fe14da
> Step 5/18 : RUN set -ex;                fetchDeps='             ca-certificates                 wget    ';      apt-get update;         apt-get install -y --no-install-recommends $fetchDeps;       rm -rf /var/lib/apt/lists/*;            dpkgArch="$(dpkg --print-architecture | awk -F- '{ print $NF }')";      wget -O /usr/local/bin/gosu "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch";         wget -O /usr/local/bin/gosu.asc "https://github.com/tianon/gosu/releases/download/$GOSU_VERSION/gosu-$dpkgArch.asc";                 export GNUPGHOME="$(mktemp -d)";        gpg --batch --keyserver ha.pool.sks-keyservers.net --recv-keys B42F6819007F00F88E364FD4036A9C25BF357DD4;     gpg --batch --verify /usr/local/bin/gosu.asc /usr/local/bin/gosu;       command -v gpgconf > /dev/null && gpgconf --kill all || :;   rm -r "$GNUPGHOME" /usr/local/bin/gosu.asc;             chmod +x /usr/local/bin/gosu;   gosu nobody true;               apt-get purge -y --auto-remove $fetchDeps
>  ---> Using cache
>  ---> 4a6e742312de
> Step 6/18 : RUN mkdir /docker-entrypoint-initdb.d
>  ---> Using cache
>  ---> 3ee76ca21bf7
> Step 7/18 : RUN apt-get update && apt-get install -y --no-install-recommends            apt-transport-https ca-certificates             pwgen           tzdata  && rm -rf /var/lib/apt/lists/*
>  ---> Using cache
>  ---> 35cbd99c0653
> Step 8/18 : ENV GPG_KEYS        177F4010FE56CA3336300305F1656F24C74CD1D8
>  ---> Using cache
>  ---> d0eca474c7eb
> Step 9/18 : RUN set -ex;        export GNUPGHOME="$(mktemp -d)";        for key in $GPG_KEYS; do                gpg --keyserver ha.pool.sks-keyservers.net --recv-keys "$key" ||             gpg --keyserver hkp://p80.pool.sks-keyservers.net:80 --recv-keys "$key" ||              gpg --keyserver hkp://ipv4.pool.sks-keyservers.net --recv-keys "$key" ||             gpg --keyserver hkp://pgp.mit.edu:80 --recv-keys "$key" ||                 gpg --keyserver pgp.mit.edu --recv-keys "$key" ||                 gpg --keyserver keyserver.pgp.com --recv-keys "$key" ;  done;   gpg --batch --export $GPG_KEYS > /etc/apt/trusted.gpg.d/mariadb.gpg;    command -v gpgconf > /dev/null && gpgconf --kill all || :;   rm -r "$GNUPGHOME";     apt-key list
>  ---> Using cache
>  ---> 08927fa8283e
> Step 10/18 : ENV MARIADB_MAJOR 10.2
>  ---> Using cache
>  ---> 656790e0a511
> Step 11/18 : ENV MARIADB_VERSION 1:10.2.24+maria~bionic
>  ---> Using cache
>  ---> b035c28bca18
> Step 12/18 : RUN set -e;        echo "deb http://ftp.osuosl.org/pub/mariadb/repo/$MARIADB_MAJOR/ubuntu bionic main" > /etc/apt/sources.list.d/mariadb.list;     {   echo 'Package: *';               echo 'Pin: release o=MariaDB';          echo 'Pin-Priority: 999';       } > /etc/apt/preferences.d/mariadb
>  ---> Using cache
>  ---> 76db9e3655f2
> Step 13/18 : RUN set -ex;       {               echo "mariadb-server-$MARIADB_MAJOR" mysql-server/root_password password 'unused';              echo "mariadb-server-$MARIADB_MAJOR" mysql-server/root_password_again password 'unused';     } | debconf-set-selections;     apt-get update;         apt-get install -y              "mariadb-server=$MARIADB_VERSION"            mariadb-backup-10.2             socat   ;       rm -rf /var/lib/apt/lists/*;    sed -ri 's/^user\s/#&/' /etc/mysql/my.cnf /etc/mysql/conf.d/*;       rm -rf /var/lib/mysql;  mkdir -p /var/lib/mysql /var/run/mysqld;        chown -R mysql:mysql /var/lib/mysql /var/run/mysqld;    chmod 777 /var/run/mysqld;   find /etc/mysql/ -name '*.cnf' -print0          | xargs -0 grep -lZE '^(bind-address|log)'              | xargs -rt -0 sed -Ei 's/^(bind-address|log)/#&/';  echo '[mysqld]\nskip-host-cache\nskip-name-resolve' > /etc/mysql/conf.d/docker.cnf
>  ---> Running in 4388923209b5
> + debconf-set-selections
> + echo mariadb-server-10.2 mysql-server/root_password password unused
> + echo mariadb-server-10.2 mysql-server/root_password_again password unused
> + apt-get update
> Get:1 http://security.ubuntu.com/ubuntu bionic-security InRelease [88.7 kB]
> Get:2 http://archive.ubuntu.com/ubuntu bionic InRelease [242 kB]
> Get:3 http://archive.ubuntu.com/ubuntu bionic-updates InRelease [88.7 kB]
> Get:4 http://archive.ubuntu.com/ubuntu bionic-backports InRelease [74.6 kB]
> Get:5 http://ftp.osuosl.org/pub/mariadb/repo/10.2/ubuntu bionic InRelease [4597 B]
> Get:6 http://security.ubuntu.com/ubuntu bionic-security/multiverse amd64 Packages [4169 B]
> Get:7 http://security.ubuntu.com/ubuntu bionic-security/universe amd64 Packages [717 kB]
> Get:8 http://security.ubuntu.com/ubuntu bionic-security/restricted amd64 Packages [5436 B]
> Get:9 http://security.ubuntu.com/ubuntu bionic-security/main amd64 Packages [535 kB]
> Get:10 http://archive.ubuntu.com/ubuntu bionic/main amd64 Packages [1344 kB]
> Get:11 http://archive.ubuntu.com/ubuntu bionic/universe amd64 Packages [11.3 MB]
> Get:12 http://archive.ubuntu.com/ubuntu bionic/multiverse amd64 Packages [186 kB]
> Get:13 http://archive.ubuntu.com/ubuntu bionic/restricted amd64 Packages [13.5 kB]
> Get:14 http://archive.ubuntu.com/ubuntu bionic-updates/multiverse amd64 Packages [7239 B]
> Get:15 http://archive.ubuntu.com/ubuntu bionic-updates/main amd64 Packages [837 kB]
> Get:16 http://archive.ubuntu.com/ubuntu bionic-updates/restricted amd64 Packages [10.8 kB]
> Get:17 http://archive.ubuntu.com/ubuntu bionic-updates/universe amd64 Packages [1220 kB]
> Get:18 http://archive.ubuntu.com/ubuntu bionic-backports/universe amd64 Packages [3918 B]
> Get:19 http://archive.ubuntu.com/ubuntu bionic-backports/main amd64 Packages [2496 B]
> Get:20 http://ftp.osuosl.org/pub/mariadb/repo/10.2/ubuntu bionic/main amd64 Packages [7257 B]
> Fetched 16.7 MB in 3s (5623 kB/s)
> Reading package lists...
> + apt-get install -y mariadb-server=1:10.2.24+maria~bionic mariadb-backup-10.2 socat
> Reading package lists...
> Building dependency tree...
> Reading state information...
> E: Version '1:10.2.24+maria~bionic' for 'mariadb-server' was not found
> ERROR: Service 'mariadb' failed to build: The command '/bin/sh -c set -ex;      {               echo "mariadb-server-$MARIADB_MAJOR" mysql-server/root_password password 'unused';           echo "mariadb-server-$MARIADB_MAJOR" mysql-server/root_password_again password 'unused';        } | debconf-set-selections;     apt-get update;      apt-get install -y              "mariadb-server=$MARIADB_VERSION"               mariadb-backup-10.2             socat   ;       rm -rf /var/lib/apt/lists/*; sed -ri 's/^user\s/#&/' /etc/mysql/my.cnf /etc/mysql/conf.d/*;  rm -rf /var/lib/mysql;  mkdir -p /var/lib/mysql /var/run/mysqld;        chown -R mysql:mysql /var/lib/mysql /var/run/mysqld;         chmod 777 /var/run/mysqld;      find /etc/mysql/ -name '*.cnf' -print0          | xargs -0 grep -lZE '^(bind-address|log)'          | xargs -rt -0 sed -Ei 's/^(bind-address|log)/#&/';      echo '[mysqld]\nskip-host-cache\nskip-name-resolve' > /etc/mysql/conf.d/docker.cnf' returned a non-zero code: 100

</code>
</details>

**Comment by tianon** [comment]
That's probably due to https://mariadb.com/resources/blog/mariadb-server-10-2-25-and-10-3-16-now-available/ -- this is pretty typical behavior for APT repos like this (new version makes the old version unavailable).

This particular build failure should be fixed by https://github.com/docker-library/mariadb/commit/f2ecbc37bcca1c61a2154dd8c677fb17504d443c.
