### ISSUE TITLE
v10.4: environment variables ignored on initializing new database

### ISSUE THREAD

**Issue by Jasper-Ben** [docker-library/mariadb#251]
docker-compose.yml:
```version: '3'
services:
    database:
        image: mariadb:10.4
        environment:
            - MYSQL_RANDOM_ROOT_PASSWORD=yes
            - MYSQL_USER=user
            - MYSQL_PASSWORD=password
            - MYSQL_DATABASE=database
        volumes:
            - ./data:/var/lib/mysql
```
./data does not yet exist.

Expected behavior:
Initializing a new database using provided environment variables.

Actual behavior:
Initialized database ignores environment variables, does not set root password, does not create custom user and creates "test" database.

Using mariadb:10.3 works as expected.

**Comment by wglambert** [comment]
Your compose file seems to be just fine

```yml
version: '3'
services:
  db:
    image: mariadb:10.4
    environment:
      - MYSQL_RANDOM_ROOT_PASSWORD=yes
      - MYSQL_USER=user
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=database
    volumes:
      - ./data:/var/lib/mysql
```
```console
$ docker-compose up -d
Starting mariadb-251_db_1_771da9625998 ... done

$ docker-compose logs | tail -n 2
db_1_771da9625998 | 2019-07-08 16:25:15 0 [Note] mysqld: ready for connections.
db_1_771da9625998 | Version: '10.4.6-MariaDB-1:10.4.6+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 3306  mariadb.org binary distribution

$ docker exec -it mariadb-251_db_1_771da9625998 mysql -u user -ppassword -D database
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 11
Server version: 10.4.6-MariaDB-1:10.4.6+maria~bionic mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [database]> show databases;
+--------------------+
| Database           |
+--------------------+
| database           |
| information_schema |
+--------------------+
2 rows in set (0.001 sec)
```

**Comment by Jasper-Ben** [comment]
Thanks for taking a look. I tried reproducing the same issue today with the same docker-compose file and this time it just worked. Weird...
I just checked and there haven't been any (major) changes to mariadb image, docker or docker-compose within my distros repository. The only thing I noticed is that I installed docker-compose right before running the command, maybe rebooting since installing fixed it. Still wouldn't explain why 10.3 worked.  Going to leave docker and docker-compose version here, just in case. Closing for now.

docker:
```
Client:
 Version:           18.09.7-ce
 API version:       1.39
 Go version:        go1.12.6
 Git commit:        2d0083d657
 Built:             Tue Jul  2 01:00:04 2019
 OS/Arch:           linux/amd64
 Experimental:      false

Server:
 Engine:
  Version:          18.09.7-ce
  API version:      1.39 (minimum version 1.12)
  Go version:       go1.12.6
  Git commit:       2d0083d657
  Built:            Tue Jul  2 00:59:35 2019
  OS/Arch:          linux/amd64
  Experimental:     false
```

docker-compose:
```
docker-compose version 1.24.1, build unknown
docker-py version: 4.0.2
CPython version: 3.7.3
OpenSSL version: OpenSSL 1.1.1c  28 May 2019
```

**Comment by andrewwippler** [comment]
I have experienced a similar `environment variables not working`. 

It appears the DB gets created, there is a pause, the environment variables are set, and the database reloads. 

My application does a loop to connect to the database and crashes before the environment variables are set. If I just wait the environment variable connection creation (it does happen) and do a `docker-compose down && docker-compose up`, I get the expected results.

Unsure why the pause is there though.

**Comment by BenjaminFavre** [comment]
Exact same problem for me with mariadb:10.4.6
I tried to downgrade to mariadb:10.3.16 and it still did not work.
Then I upgraded docker from 18.09.06 to 18.09.08 and it started to work with mariadb:10.3.16.
But still not working with mariadb:10.4.6
Docker-compose version : 1.24.1

**Comment by thenktor** [comment]
I had an issue when installing latest mariadb (10.4.7) using docker-compose:
> version: '3.1'
> 
> services:
> 
>   db:
>     image: mariadb
>     volumes:
>       - /docker/mariadb:/var/lib/mysql
>     restart: always
>     ports:
>       - 3306:3306
>     environment:
>       MYSQL_ROOT_PASSWORD: mypass
>       MYSQL_ROOT_HOST: "%"
> 
>   adminer:
>     image: adminer
>     restart: always
>     ports:
>       - 8080:8080

The environment variables were set inside the container but mariadb apparantly did not set the password. I was unable to login (tried several times).
Then I've used mariadb:10.2 which worked on first attempt.

**Comment by acelaya** [comment]
In case it helps figuring out this issue, I'm experiencing the same issue with the next docker-compose config:

```yaml
version: '3'

services:
  db_maria:
      container_name: db_maria
      image: mariadb:10.2
      ports:
          - "3308:3306"
      volumes:
          - ./data/infra/database:/var/lib/mysql
      environment:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: my_cool_database
```

I have tried with versions `10.2`, `10.3` and `10.4` with the same result.

The container logs when running `docker-compose up` are these:

```
Initializing database


PLEASE REMEMBER TO SET A PASSWORD FOR THE MariaDB root USER !
To do so, start the server, then issue the following commands:

'/usr/bin/mysqladmin' -u root password 'new-password'
'/usr/bin/mysqladmin' -u root -h  password 'new-password'

Alternatively you can run:
'/usr/bin/mysql_secure_installation'

which will also give you the option of removing the test
databases and anonymous user created by default.  This is
strongly recommended for production servers.

See the MariaDB Knowledgebase at http://mariadb.com/kb or the
MySQL manual for more instructions.

Please report any problems at http://mariadb.org/jira

The latest information about MariaDB is available at http://mariadb.org/.
You can find additional information about the MySQL part at:
http://dev.mysql.com
Consider joining MariaDB's strong and vibrant community:
https://mariadb.org/get-involved/

Database initialized
MySQL init process in progress...
2019-10-06  9:11:21 140196928062784 [Note] mysqld (mysqld 10.2.27-MariaDB-1:10.2.27+maria~bionic) starting as process 89 ...
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Uses event mutexes
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Compressed tables use zlib 1.2.11
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Using Linux native AIO
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Number of pools: 1
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Using SSE2 crc32 instructions
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Initializing buffer pool, total size = 256M, instances = 1, chunk size = 128M
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Completed initialization of buffer pool
2019-10-06  9:11:21 140196206118656 [Note] InnoDB: If the mysqld execution user is authorized, page cleaner thread priority can be changed. See the man page of setpriority().
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Highest supported file format is Barracuda.
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: 128 out of 128 rollback segments are active.
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Creating shared tablespace for temporary tables
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Setting file './ibtmp1' size to 12 MB. Physically writing the file full; Please wait ...
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: File './ibtmp1' size is now 12 MB.
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: Waiting for purge to start
2019-10-06  9:11:21 140196928062784 [Note] InnoDB: 5.7.27 started; log sequence number 1620069
2019-10-06  9:11:21 140195835926272 [Note] InnoDB: Loading buffer pool(s) from /var/lib/mysql/ib_buffer_pool
2019-10-06  9:11:21 140196928062784 [Note] Plugin 'FEEDBACK' is disabled.
2019-10-06  9:11:21 140196928062784 [Warning] 'user' entry 'root@4130cd423d48' ignored in --skip-name-resolve mode.
2019-10-06  9:11:21 140196928062784 [Warning] 'proxies_priv' entry '@% root@4130cd423d48' ignored in --skip-name-resolve mode.
2019-10-06  9:11:21 140195835926272 [Note] InnoDB: Buffer pool(s) load completed at 191006  9:11:21
2019-10-06  9:11:21 140196928062784 [Note] Reading of all Master_info entries succeeded
2019-10-06  9:11:21 140196928062784 [Note] Added new Master_info '' to hash table
2019-10-06  9:11:21 140196928062784 [Note] mysqld: ready for connections.
Version: '10.2.27-MariaDB-1:10.2.27+maria~bionic'  socket: '/var/run/mysqld/mysqld.sock'  port: 0  mariadb.org binary distribution
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
```

It's even warning that a password should be set.

However, I left it running for a while (1 or 2 minutes), and it suddenly printed more output, and then honored the env vars, creating the `my_cool_database` database, and setting the password.

**Comment by b12f** [comment]
I'm experiencing the same issue. Volume is new and empty, env variables are set, yet even after 10 minutes of waiting and trying a `docker restart` no extra user has been created or root password set.

**Comment by wglambert** [comment]
Your guys' issue seems related to https://github.com/docker-library/mariadb/issues/262

A workaround is to skip the timezone configuration https://github.com/docker-library/mariadb/issues/262#issuecomment-536405303

**Comment by hAbd0u** [comment]
In my case the issue was the mount directory ownership, eventually I let docker choose it for me, I know this is not security best practice but this what it does worked for me.

**Comment by pushpdeep** [comment]
I had a similar problem. I simply replaced MYSQL with MARIADB and everything worked fine.
MARIADB_DATABASE=mydb
MARIADB_USER=myuser
MARIADB_PASSWORD=mypassword
MARIADB_ROOT_PASSWORD=strongpassword
works with mariadb:latest

**Comment by grooverdan** [comment]
@pushpdeep there's also `MARIADB_ROOT_PASSWORD_HASH` and `MARIADB_PASSWORD_HASH` now too.

The `MYSQL_*` names are still meant to work and there are test cases that cover these. Please open a new issue _with details_ if there are problems. The causes of the original problem here where closed a while ago.

**Comment by Aiddy81** [comment]
Hey Everyone, just came here to say I had been experiencing the same issue across different versions of the Mariadb docker and did also notice the slight pause as well.

I spent some time trying to get it to work, tried many of things mentioned here and bunch of other things with no luck. But after having a bit more of a think and play around I discovered that if I added the below how it's shown it setup the root password and the user without issue.


MARIADB_DATABASE: ${MARIADB_NAME}
MARIADB_USER: ${MARIADB_USERNAME}
MARIADB_PASSWORD: ${MARIADB_PASSWORD}
MARIADB_ROOT_PASSWORD: ${MARIADB_ROOTPASSWORD}
MYSQL_ROOT_PASSWORD: ${MARIADB_ROOTPASSWORD}
MYSQL_USER: ${MARIADB_USERNAME}
MYSQL_PASSWORD: ${MARIADB_PASSWORD}

It's probably not the best or lose elegant way but the only why o could get it to set up the root password and the user for Mariadb.

Hope this helps

**Comment by scotton34** [comment]
Recently I had this issue and was scratvching my head for a while... I set my docker-compose.yml file to have 
environment:
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MYSQL_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}

Then set my .env

**Comment by grooverdan** [comment]
You only need to set `MARIADB_*` environment variables.

Please open a new issue with details if there are problems. The causes of the original problem here where closed a while ago.
