### ISSUE TITLE
MYSQL_HOST:localhost: command not found

### ISSUE THREAD

**Issue by EngrArslanLiaqat** [docker-library/mariadb#252]
Creating an image for mariadb dump. Cannot establish connection to mariadb container. I have a container running MariaDB. I am developing my image for creating MySQL dump of the database periodically. Connection between mariadump container and MariaDB container could not be established.

```
#!/bin/bash

MYSQL_USER=wordpress
MYSQL_PASSWORD=wordpress
MYSQL_HOST=localhost
MYSQL_PORT=3306

BACKUP_FILE=/var/backups/$(date +"%Y-%m-%d-%H%M%S")_${MYSQL_HOST}_mysqldump

MYSQL_OPTS="-u${MYSQL_USER} -p${MYSQL_PASSWORD} -h${MYSQL_HOST} -P${MYSQL_PORT}"
MYSQLDUMP_OPTS="--single-transaction --routines --triggers"

mysqldump ${MYSQL_OPTS} ${MYSQLDUMP_OPTS} --all-databases >${BACKUP_FILE}
RETVAL=$?

if [ "$RETVAL" == 0 ]; then
  echo Compressing backup using gzip compression method.
  gzip --best ${BACKUP_FILE}*
  RETVAL=$?
fi

if [ "$RETVAL" == 0 ]; then
    echo Backup finished successfully.
    exit 0 
else
    echo Backup failed with errors!
    exit 1
fi
```
Error:
`MYSQL_HOST:localhost: command not found`

if I use `MYSQL_HOST=host.docker.internal`
Error:
`2013: “Lost connection to MySQL server at 'handshake: reading inital communication packet', system error: 115” when trying to connect`

**Comment by wglambert** [comment]
If you tell mysql to use `localhost` it will use the unix socket, if you change that to 127.0.0.1 then it should work

**Comment by wglambert** [comment]
Closing since this seems resolved
