### ISSUE TITLE
MariaDB Slow Performance In Docker!!!

### ISSUE THREAD

**Issue by shiyingzhe** [docker-library/mariadb#254]
I use sysbench to test MariaDB:10.3 inside Docker, and the performance is so bad. 
MariaDB  with same .cnf and datadir running on Centos physical Host  is 2X+ time faster than Mairdb inside Docker. 
The result is here:
|             | TPS        | QPS         | lat(ms,min) | lat (ms,avg) | lat (ms,max) | lat (ms,95%) |
| physical| 2457.54 | 49152.68 | 9.28           |55.96          | 349.71         | 77.19 |
| docker | 1288.76 | 25288.43 | 27.50          |79.06          | 174.91         | 108.68 |

**Comment by shiyingzhe** [comment]
When I use mysql:5.7 inside Docker, the result is better
|   | TPS | QPS | lat(ms,min) | lat (ms,avg) | lat (ms,max) | lat (ms,95%) |
| phisical | 2361.14 | 47224.81 | 11.41 |42.33 | 275.57 | 81.48 |
| docker | 2167.09 | 43342.53 | 10.14 |46.13 | 1677.70 | 86.00 |

**Comment by yosifkit** [comment]
We only install MariaDB packages from upstream:
https://github.com/docker-library/mariadb/blob/9787916251cc63546d638ea0ef28e55fd2e44868/10.3/Dockerfile#L83

Unless you are also installing this exact package (including version) on your CentOS host, it is not a fair comparison.

**Comment by shiyingzhe** [comment]
> 
> 
> We only install MariaDB packages from upstream:
> 
> https://github.com/docker-library/mariadb/blob/9787916251cc63546d638ea0ef28e55fd2e44868/10.3/Dockerfile#L83
> 
> Unless you are also installing this exact package (including version) on your CentOS host, it is not a fair comparison.
I check the version, mariadb on centos7 is 10.3.15-MariaDB。And mariadb inside docker is 10.3.14-MariaDB-1:10.3.14+maria~bionic

**Comment by shiyingzhe** [comment]
I use same version image, the result is still not good.

**Comment by tianon** [comment]
You duplicated the setup completely to compare apples to apples
appropriately?

As in, set up a system running the same release of Ubuntu, install the same
package, run tests, then uninstall, wipe the db, mount the exact same
storage directory inside a container on the same exact kernel and run
performance tests again.

**Comment by shiyingzhe** [comment]
@tianon First, thx for your reply.  I run mariadb and docker on same host. mount the same directory. But it not work. The operation system is CentOS Linux release 7.4.1708 (Core). I'll change my system to test again.

**Comment by shiyingzhe** [comment]
@tianon I use centos as base image to build mariadb image and the performance is good. So i guess that offical image based ubuntu may affect the performance when run the container on centos host.

**Comment by danielstern** [comment]
Confirming this issue still exists

**Comment by grooverdan** [comment]
@danielstern please provide details of your test including:
* Host OS version
* Host kernel version
* Host RAM total
* Host storage information
* Host container runtime and version
* Storage used by container runtime and the filesystem that backs this
* MariaDB container (full version)
* MariaDB command line options/configuration
* Test type, and parameters used to conduct the test. If not a public test some details like read/write mix of queries

Did you do the comparison with a native MariaDB package of the version and configuration?

**Comment by mgagnant** [comment]
Hi I have also very bad performances. I try to explain. All my hosts are with ADVANCE-2 servers @OVH. 
- Hosts OS : Debian 11
- Host RAN 64 GB
- Host storage : 2x6to RAID1 with glusterFS (for clustering)
- Docker last version
- mariadb:latest https://hub.docker.com/_/mariadb
PHP container is on one host and mariadb container on another with Private network bandwith at 2GB/s
When my PHP app launch query on mariadb container it is very slow !
How can I improve performances please ?
Micka

**Comment by grooverdan** [comment]
Please ask on https://www.reddit.com/r/mariadb/ or https://dba.stackexchange.com/.

Include `SHOW GLOBAL STATUS` after 24hrs of uptime. If its a query being slow include `explain format=json select ....` output. Explain what you are comparing the bad performance to.

Have you performance tested the glusterFS? Its not tested and as a clustered FS contains overheads not present on other filesystems.

**Comment by grooverdan** [comment]
As [glusterFS](https://github.com/gluster/glusterfs/issues/3867) is slow for you, that's the likely cause.

**Comment by mgagnant** [comment]
Hello grooverdan,
thanks for your reply.
I put my mariadb containers directly on SSD (without glusterfs) and my php container also on SSD but on another datacenter/server and it is very slow.

**Comment by grooverdan** [comment]
Use the above forums and show details. Also see https://mysqlperf.github.io/mysql/skrunfilter/
