### ISSUE TITLE
Failing to start MariaDB as an unprivileged user

### ISSUE THREAD

**Issue by o-alquimista** [docker-library/mariadb#256]
This is the Compose file where it concerns MariaDB:
```
  mariadb:
    build: "./mariadb/"
    container_name: mariadb
    user: "200001:200000"
    networks:
      database:
        ipv4_address: 172.19.2.3
    volumes:
      - database:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: test
      MYSQL_DATABASE: testdatabase
      MYSQL_USER: test
      MYSQL_PASSWORD: test
```
The `database` volume is defined in the top-level `volumes` section.

This is the Dockerfile:
```
FROM mariadb:10.4

# Create user and group
RUN groupadd -g 200000 dailyprophet
RUN useradd -u 200001 -g 200000 dailyprophet

# Set ownership of the mysql directory
RUN chown -R 200001:200000 /var/lib/mysql

WORKDIR /var/lib/mysql
```

This is the output from `docker-compose logs mariadb`:
```
Attaching to mariadb
mariadb     | Initializing database
mariadb     | 2019-07-19 12:51:46 0 [Warning] Can't create test file /var/lib/mysql/89743377d1c0.lower-test
mariadb     | 2019-07-19 12:51:46 0 [ERROR] mysqld: Can't create/write to file '/var/lib/mysql/aria_log_control' (Errcode: 13 "Permission denied")
mariadb     | 2019-07-19 12:51:46 0 [ERROR] mysqld: Got error 'Can't create file' when trying to use aria control file '/var/lib/mysql/aria_log_control'
mariadb     | 2019-07-19 12:51:46 0 [ERROR] Plugin 'Aria' init function returned error.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] Plugin 'Aria' registration as a STORAGE ENGINE failed.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] InnoDB: The error means mysqld does not have the access rights to the directory.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] InnoDB: Operating system error number 13 in a file operation.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] InnoDB: The error means mysqld does not have the access rights to the directory.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] InnoDB: Cannot open datafile './ibdata1'
mariadb     | 2019-07-19 12:51:46 0 [ERROR] InnoDB: Could not open or create the system tablespace. If you tried to add new data files to the system tablespace, and it failed here, you should now edit innodb_data_file_path in my.cnf back to what it was, and remove the new ibdata files InnoDB created in this failed attempt. InnoDB only wrote those files full of zeros, but did not yet use them in any way. But be careful: do not remove old data files which contain your precious data!
mariadb     | 2019-07-19 12:51:46 0 [ERROR] InnoDB: Database creation was aborted with error Cannot open a file. You may need to delete the ibdata1 file before trying to start up again.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] Plugin 'InnoDB' init function returned error.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] Plugin 'InnoDB' registration as a STORAGE ENGINE failed.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] Failed to initialize plugins.
mariadb     | 2019-07-19 12:51:46 0 [ERROR] Aborting
mariadb     | 
mariadb     | Installation of system tables failed!  Examine the logs in
mariadb     | /var/lib/mysql/ for more information.
mariadb     | 
mariadb     | The problem could be conflicting information in an external
mariadb     | my.cnf files. You can ignore these by doing:
mariadb     | 
mariadb     |     shell> /usr/bin/mysql_install_db --defaults-file=~/.my.cnf
mariadb     | 
mariadb     | You can also try to start the mysqld daemon with:
mariadb     | 
mariadb     |     shell> /usr/sbin/mysqld --skip-grant-tables --general-log &
mariadb     | 
mariadb     | and use the command line tool /usr/bin/mysql
mariadb     | to connect to the mysql database and look at the grant tables:
mariadb     | 
mariadb     |     shell> /usr/bin/mysql -u root mysql
mariadb     |     mysql> show tables;
mariadb     | 
mariadb     | Try 'mysqld --help' if you have problems with paths.  Using
mariadb     | --general-log gives you a log in /var/lib/mysql/ that may be helpful.
mariadb     | 
mariadb     | The latest information about mysql_install_db is available at
mariadb     | https://mariadb.com/kb/en/installing-system-tables-mysql_install_db
mariadb     | You can find the latest source at https://downloads.mariadb.org and
mariadb     | the maria-discuss email list at https://launchpad.net/~maria-discuss
mariadb     | 
mariadb     | Please check all of the above before submitting a bug report
mariadb     | at http://mariadb.org/jira
mariadb     | 

```

A quick look and it seems like a permission issue, which is why I am running `chown` in the Dockerfile, but it doesn't change the outcome. What now?

**Comment by o-alquimista** [comment]
By running the image I built and looking at /var/lib/mysql, it is clear that the `chown` command isn't doing its job here. Funny, because I do that in other images, such as httpd:
```
FROM httpd:2.4

# Create user and group
RUN groupadd -g 200000 dailyprophet
RUN useradd -u 200001 -g 200000 dailyprophet

# Set Unix socket permissions
RUN mkdir /var/run/php
RUN chown -R 200001:200000 /var/run/php
RUN chmod -R g+w /var/run/php

# Set ownership of the apache2 directory
RUN chown -R 200001:200000 /usr/local/apache2

# copy config commands...
(...)

WORKDIR /usr/local/apache2/htdocs/
```
And it works for httpd, and I do the same for php, composer, node, etc. The volumes and bind mounts are defined in the Compose file, same as MariaDB. Something in this image makes us unable to use `chown`. I'm curious about the why.

**Comment by yosifkit** [comment]
> EDIT: Now I understand your image defines VOLUME in its Dockerfile, which is why chown isn't working as I expect. I've opted to use a bind mount for now, so I can fix its ownership from the host.

Correct. If you want to run as an unprivileged user, you need to provide a directory that is writable for that user. As you discovered, docker doesn't allow you to change the Volume permissions after it is defined.

You could just let the image run without changing the user and it will chown as necessary to `mysql` and then drop from root to the `mysql` user.

https://github.com/docker-library/mariadb/blob/ef12d140f19ace81b65f2b9aba9bf02b51ae888e/docker-entrypoint.sh#L68-L74

**Comment by o-alquimista** [comment]
@yosifkit 
Thanks for the info. I'm still curious about why the VOLUME has to be defined there.

**Comment by yosifkit** [comment]
> I'm still curious about why VOLUME is there

It has been there since the beginning and is the only reliable way to tell users that this is where the mutable important data is.

> Will this work if you bring in pre-existing database files?

So, you have a directory of pre-existing files, say `/host/mariadb`. You use them with the MariaDB image via a bind mount `-v /host/mariadb:/var/lib/mysql`. If you don't add `--user`, then the container will use `root` to chown the files to the `mysql` user of the container (line 72 in my previous comment) before becoming the `mysql` user. The host will see them as owned by user id `999`. It looks like it currently doesn't change group ownership or permissions.

If you want to preserve the ownership of the existing database files, then you just need to run mariadb as a user id with access to the files. E.x. `/host/mariadb` is owned by user `1000` and group `1001` (`ls -ln`), then run mariadb with `--user 1000:1001`.

**Comment by o-alquimista** [comment]
@yosifkit 
I think I get it. With bind mounts we can control the ownership of the data directory. With docker-managed volumes, we are stuck with the `mysql` user.

I've decided to have a data/ directory within my project directory and run MariaDB as my UID:GID (1000:1000 in this case). This project of mine is on GitHub, so I don't want to have to set `data/` ownership to 200001:200000 or 999:999 every time I clone it here. It will be owned by whoever clones it.

Thanks for the info. I believe this can be closed now.

**Comment by o-alquimista** [comment]
An update. I finally have MariaDB running as an arbitrary user.

I'm adjusting permissions for:
- socket directory: `/run/mysqld`
- data directory: `/var/lib/mysql/`

And both of these directories are in Docker-managed volumes, not bind mounts.

```Dockerfile
# syntax=docker/dockerfile:1
FROM mariadb:10.6 AS mariadb

ARG USER_ID
ARG GROUP_ID

RUN chown -R ${USER_ID}:${GROUP_ID} /var/lib/mysql/ && \
  chmod -R 770 /var/lib/mysql/ && \
  chown -R ${USER_ID}:${GROUP_ID} /run/mysqld && \
  chmod -R 770 /run/mysqld
```

The resulting image behaves properly when you run it, regardless of whether the data directory is initialized or not.

I hope this helps others in the future.
