### ISSUE TITLE
The Timezone Environment Variable

### ISSUE THREAD

**Issue by zx1986** [docker-library/mariadb#26]
Could we just do this in docker-entrypoint.sh?

```
...

if [ "$TIMEZONE" ]; then
  echo $TIMEZONE > /etc/timezone && dpkg-reconfigure -f non interactive tzdata
fi

# sed is for https://bugs.mysql.com/bug.php?id=20545
mysql_tzinfo_to_sql /usr/share/zoneinfo | sed 's/Local time zone must be set--see zic manual page/FCTY/' | "${mysql[@]}" mysql

...
```

I just need MySQL to run in my local timezone.
Or is there better way to do this?

**Comment by ypid** [comment]
What about `--env "TZ=Europe/Berlin"` to set the timezone to Europe/Berlin for example? Should be enough.

**Comment by zx1986** [comment]
https://github.com/docker-library/mariadb/pull/25

@ypid Thanks!
I am so stupid ....

**Comment by systec-electronic** [comment]
@zx1986 , @ypid Could you please explain to me what we need to change, please?
I have the same problem...
thanks.

**Comment by zx1986** [comment]
@systec-electronic Hello, I added these into my Dockerfile:

```
ENV TZ=Asia/Taipei
RUN ln -snf /usr/share/zoneinfo/$TZ /etc/localtime && echo $TZ > /etc/timezone
```

**Comment by systec-electronic** [comment]
@zx1986 Thanks, but unfortunately it isn't working for me.
