### ISSUE TITLE
How to run mariadb with root user

### ISSUE THREAD

**Issue by quangvuptit** [docker-library/mariadb#263]
when I entered container and use root priviledge with gosu, everything is ok. But when I run a script  in docker-entrypoint with root priviledge to write file, it wasn't allowed.

**Comment by wglambert** [comment]
The entrypoint runs as the non-root `mysql`
https://github.com/docker-library/mariadb/blob/bf675caa56e4a1b462c665d1cded137f13c33753/10.4/docker-entrypoint.sh#L7
https://github.com/docker-library/mariadb/blob/bf675caa56e4a1b462c665d1cded137f13c33753/10.4/docker-entrypoint.sh#L67-L74
