### ISSUE TITLE
Please bump version

### ISSUE THREAD

**Issue by StephenLittBelch** [docker-library/mariadb#273]
MariaDB 10.4.9, 10.3.19, 10.2.28, and 10.1.42 have been released (I wasn’t sure how to best create a pull request to help update the tags/builds). Thank you.

**Comment by yosifkit** [comment]
Thanks. The updates are automated by this job: https://doi-janky.infosiftr.net/job/update.sh/job/mariadb/ which runs `update.sh` in this repo, builds and tests the images, and commits the result.  I'll give it a poke.

See https://github.com/docker-library/mariadb#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet for what happens after to get the images on the Docker Hub.

**Comment by richardhd** [comment]
Strangely, if you [look here](https://github.com/docker-library/mariadb/commits/master/10.4), you'll see a commit for the new version (10.4.9), followed by a commit for the old version (10.4.8) on the same day.

**Comment by yosifkit** [comment]
Those releases aren't on https://downloads.mariadb.org/mariadb/+releases/ and so `update.sh` skipped them. My guess is that there was a problem with them.

See https://github.com/docker-library/official-images/pull/6947 for the PR to get them built for the Docker Hub.
