### ISSUE TITLE
open_tables count is increasing with >=mariadb:10.1.36

### ISSUE THREAD

**Issue by umagmrit** [docker-library/mariadb#276]
open_tables count is increasing with >=mariadb:10.1.36. But this is not with mariadb:10.1.35.
https://github.com/MariaDB/server/commit/64a23c1c8a826a6f58f8a415f60a0e3cc0e0375f
After commenting out the if-statement in sql/sql_base.cc from above commit issue is resolved.
 if-statement : if (table_list->table->file->referenced_by_foreign_key())
Could you please help me on this.  Am I missing any configuration?

**Comment by wglambert** [comment]
This seems like an upstream issue, I don't think there's anything for us to do in this area

**Comment by umagmrit** [comment]
I have not faced this issue with mariadb:10.1.35. After upgrade to 10.1.36 I am facing this issue. And I have tried by removing MariaDB/server@64a23c1 this commit, and it is working fine. When the load is increases open_tables count crossing limit of 2000 and goes beyond one lakh , but this not with 10.1.35.

**Comment by wglambert** [comment]
This repo is for the Docker image of MariaDB, you'll want to file your issue with the appropriate MariaDB resource https://github.com/MariaDB/server#bug-reports as we're unaffiliated with its development
