### ISSUE TITLE
Issue #264 Still Happening - Can't connect to MariaDB from another container.

### ISSUE THREAD

**Issue by shawnweeks** [docker-library/mariadb#285]
I don't see where #264 gave an actual solution and I'm running into the same issue with the lastet release. What is the actual fix? here is my docker command.

`docker run -d \
    --name mariadb \
    -eMYSQL_ROOT_PASSWORD='XU5VwXhvjmkMR4hSZS3xtB2Z7FSeGvea' \
    --network=proxy-network \
    -v /volume1/Docker/mariadb/data:/var/lib/mysql \
    mariadb:latest`

And the exception
`2020-01-17 17:12:11 9 [Warning] Aborted connection 9 to db: 'unconnected' user: 'unauthenticated' host: '172.18.0.2' (This connection closed normally without authentication)`

**Comment by shawnweeks** [comment]
MariaDB error handling is deplorable. Issue was caused by host not being allowed to connect. An error that only shows up when you try and connect with a real client.

**Comment by UntouchedWagons** [comment]
So what's the solution?

**Comment by lopugit** [comment]
bump

**Comment by TheloTheGreat** [comment]
Unrelated to docker, but I had a similar problem after a clean installation of MariaDB and google brought me here, so I might as well post my solution. I had to manually grant privileges to my mysql user to be able to connect remotely, by doing a mysql command such as:
GRANT ALL PRIVILEGES ON *.* TO 'myuser'@'.%' IDENTIFIED BY 'mypassword' WITH GRANT OPTION;
FLUSH PRIVILEGES;
