### ISSUE TITLE
Image prefers UID:GID 999:999

### ISSUE THREAD

**Issue by hathalud** [docker-library/mariadb#287]
MariaDB Docker image for 1:10.4.12 has an /etc/passwd that specifies a UID:GID setting 999:999, which is not the UID and GID that are passed to the image. I usually use a single user and group for most of my Docker containers since most all work with each other. While I don't mind having an oddball, it would have been nice if the documentation was more clear about what steps were needed to use a custom UID and GID. Or if this was a mistake, it needs to be fixed in the next version. As it was, it took me a little while to realize that my UID:GID Docker Variables were not being used correctly and that was why MariaDB was throwing permission errors at me. Thank you for all the great work on MariaDB though!

**Comment by wglambert** [comment]
>999:999, which is not the UID and GID that are passed to the image.

The Dockerfile creates the user/group `mysql`
https://github.com/docker-library/mariadb/blob/4c69dec03b0b771563c8474ab358b7812edbfc88/10.4/Dockerfile#L5

Which is `999:999` in the image
```console
$ docker run -d --rm --name mariadb -e MYSQL_ROOT_PASSWORD=root mariadb:10.4.12
a40728c1f117b5096f8554da8bd202ef895a8aed9fe7846551dc3cf269567534

$ docker exec -it mariadb bash

root@a40728c1f117:/# cat /etc/passwd | grep mysql
mysql:x:999:999::/home/mysql:/bin/sh
```

For running MariaDB as an arbitrary user see https://github.com/docker-library/docs/tree/master/mysql#running-as-an-arbitrary-user
Which will make the processes in the container run as that user and all database files initialized will be owned by that user

This is on https://labs.play-with-docker.com/ (Alpine) to workaround https://github.com/docker-library/mariadb/issues/262
```console
$ addgroup -g 1337 test
$ adduser -u 1337 -G test test
$ cat /etc/passwd | grep test
test:x:1337:1337:Linux User,,,:/home/test:/bin/bash

$ mkdir testdir && chown test:test testdir

$ docker run -d --user 1337:1337 --name mariadb -v /etc/passwd:/etc/passwd:ro -v "$PWD"/testdir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root mariadb:10.4.129190db34a9df6ff85c52286e222c87c1d459fad2753c1cc50f97f8076e4e0edf

$ docker exec -it --user 1337:1337 mariadb bash
groups: cannot find name for group ID 1337

test@9190db34a9df:/$ echo $UID; groups
1337
groups: cannot find name for group ID 1337
1337

test@9190db34a9df:/$ ps aux
USER        PID %CPU %MEM    VSZ   RSS TTY      STAT START   TIME COMMAND
test          1  0.2  0.2 1987256 87484 ?       Ssl  18:49   0:00 mysqld
test        178  0.0  0.0  18504  3356 pts/0    Ss   18:50   0:00 bash
test        194  0.0  0.0  34396  2820 pts/0    R+   18:51   0:00 ps aux

$ ls -al testdir
total 141076
drwxr-xr-x    4 test     test           208 Feb  4 18:49 .
drwx------    1 root     root            21 Feb  4 18:49 ..
-rw-rw----    1 test     test      18620416 Feb  4 18:49 aria_log.00000001
-rw-rw----    1 test     test            52 Feb  4 18:49 aria_log_control
-rw-rw----    1 test     test           976 Feb  4 18:49 ib_buffer_pool
-rw-rw----    1 test     test      50331648 Feb  4 18:49 ib_logfile0
-rw-rw----    1 test     test      50331648 Feb  4 18:49 ib_logfile1
-rw-rw----    1 test     test      12582912 Feb  4 18:49 ibdata1
-rw-rw----    1 test     test      12582912 Feb  4 18:49 ibtmp1
-rw-rw----    1 test     test             0 Feb  4 18:49 multi-master.info
drwx------    2 test     test          4096 Feb  4 18:49 mysql
drwx------    2 test     test            20 Feb  4 18:49 performance_schema
```

**Comment by hansaplasst** [comment]
This issue still isn't resolved in Ubuntu 20.04...

I finally got it working using the above solution.
However, what's missing in @wglambert's response is that `/etc/group:/etc/group:ro` should be in there as well. Else you get group errors. 
```
docker run -d --user 1337:1337 --name mariadb -v /etc/passwd:/etc/passwd:ro -v /etc/group:/etc/group:ro -v "$PWD"/testdir:/var/lib/mysql -e MYSQL_ROOT_PASSWORD=root mariadb:latest`
```

Since a lot of us are using docker-compose, I've also included a solution based on dc below for completeness.

```
  mariadb:
    image: mariadb:latest
    container_name: mariadb
    restart: always
    user: "1337:1337"
    environment:
      MARIADB_ROOT_PASSWORD: "secret"
    ports:
      - 3306:3306
    volumes:
      - /home/dockr/mnt/kodi-headless/mariadb:/var/lib/mysql
      - /etc/passwd:/etc/passwd:ro
      - /etc/group:/etc/group:ro
```

Cheers

**Comment by grooverdan** [comment]
Hi, to help me understand the issue more, why is a user/group resolution of `1337:1337` to `test` (or actual user/group) needed inside the container?

**Comment by hansaplasst** [comment]
First of all. Thanks for the awesome work you've done!

In reply to your comment. 
Maybe I was a bit too conservative as to state that the D-user **must** have an equivalent user in the host. Let's trust that Linus has fixed all the bugs and that "insane" users are handled appropriately ;-) I've updated my answer from "must" to "my opinion" and "should"...

Nevertheless, I don't like seeing "systemd-coredump:systemd-coredump" on my docker paths... It looks wrong. Just like 999:999 looks wrong. IMHO. Docker or (until there a cure) sysadmins and image builders should handle the "insane" users and not Linus. But that's just my opinion ;-)

The issue remains that the mariadb image UID:GID can't be changed as I would have expected by just passing the arguments for UID and GID via -e or --user.

-H

**Comment by grooverdan** [comment]
As you can see from other container runtimes, running rootless/unprivileged containers, there's uid/gid maps (but not user/group maps) between host and container so they aren't necessary the same (ref: [blog](https://blog.christophersmart.com/2021/01/26/user-ids-and-rootless-containers-with-podman/), [Red Hat blogs/docs](https://www.redhat.com/sysadmin/rootless-podman-makes-sense)). Even [docker has rootless mode](https://docs.docker.com/engine/security/rootless/).

I'm looking to add a test to the [test suite](https://github.com/MariaDB/mariadb-docker/tree/master/.test). Just trying to write it to account for rootful/rootless modes concurrently.

See also #256.
