### ISSUE TITLE
Utf8mb4 character set for SQL files in /docker-entrypoint-initdb.d

### ISSUE THREAD

**Issue by xjuric29** [docker-library/mariadb#289]
I have a Docker image with own character configuration in container /etc/mysql/conf.d which contains this:

```
[mysqld]
#
# * Character sets
#
# MySQL/MariaDB default is Latin1, but in Debian we rather default to the full
# utf8 4-byte character set. See also client.cnf
#
character-set-server  = utf8mb4
collation-server      = utf8mb4_general_ci
```

And in directory /docker-entrypoint-initdb.d I copy two sql files. The first for creation of database structure and the second for filling the database with sample czech data. But unfortunately when I run the container, diacritics characters are "damaged".

![sql](https://user-images.githubusercontent.com/26231120/74990832-a3c00080-5444-11ea-8a1a-5cc10aff4dbd.png)

If I try a query `SHOW VARIABLES LIKE '%character%';` I get right output

```
character_set_client	utf8mb4
character_set_connection	utf8mb4
character_set_database	utf8mb4
character_set_filesystem	binary
character_set_results	utf8mb4
character_set_server	utf8mb4
character_set_system	utf8
character_sets_dir	/usr/share/mysql/charsets/
```

and when I insert some new rows, inserted text is alright. Can you please tell me what I do wrong?

**Comment by yosifkit** [comment]
That sounds like we need basically the same fix as https://github.com/docker-library/mysql/pull/639
