### ISSUE TITLE
Ansible does not default enough time to initialize database and root password

### ISSUE THREAD

**Issue by smacz42** [docker-library/mariadb#298]
See related here: https://github.com/ansible/ansible/issues/68803 Ansible's default timeout configuration kills the container before it is able to create a root password, and is therefore you are able to log into the database as root without a password. Ansible is reporting this as succeeded, so there is no good way to determine that this wasn't ever set.

Just thought you might like a heads up.

**Comment by tianon** [comment]
This might be related to #262, too.

**Comment by grooverdan** [comment]
With #262 resolved, can you please confirm if this is fixed using any the latest major release released yesterday

**Comment by smacz42** [comment]
I will try it out.

**Comment by smacz42** [comment]
I tried it out with 10.5, and did not run into that issue. Closing.
