### ISSUE TITLE
[Question] CentOS 7?

### ISSUE THREAD

**Issue by qops1981** [docker-library/mariadb#3]
Hey Guys, I am new to docker and teaching myself. Is it easy to make this work in a CentOS Container? I noted in the Docker code there were "get-apt" commands leading me to believe this was a debian based container.

**Comment by tianon** [comment]
This is a Debian-based container, but I'm curious why you need a CentOS-based container?  You shouldn't have any problem running this container as-is on a CentOS 7 host without worrying about what the container's userspace is.

**Comment by qops1981** [comment]
I guess I don't need one then. I am a novice so I assumed that if I was running Docker on CentOS that the Containers had to match as a requirment. Learning as I go :-) Thank you again! :-)

**Comment by tianon** [comment]
Naw, that's one of my favorite use-cases for Docker!  I actually run Gentoo on many of my machines, but none of my containers have Gentoo in them. :+1:
