### ISSUE TITLE
mount as user mysql

### ISSUE THREAD

**Issue by note89** [docker-library/mariadb#30]
Hello i would like to mount a volume as another user than root. 
but mysql does not has access to chown: cannot read directory '/var/lib/mysql/': Permission denied

**Comment by yosifkit** [comment]
Yes, the [data directory is chowned](https://github.com/docker-library/mariadb/blob/034c283be05caa5e465047ce19f1770647eadd74/docker-entrypoint.sh#L100) to the `mysql` user before `mysqld` is started.  This does not work on Macs where the directory is actually a share through vboxsf.  Some solutions are discussed in https://github.com/boot2docker/boot2docker/issues/581.  If you are in this boat of being unable to change the ownship of the directory that gets bind-mounted, I would think the easiest (without using the experimental [user namespaces](https://github.com/docker/docker/blob/master/experimental/userns.md)) would be to create an image `FROM mariadb:10` that changes the user id of the `mysql` user.

**Comment by motin** [comment]
I tried using the same [workaround fro OSX that worked with the mysql docker image](https://github.com/docker-library/mysql/issues/99#issuecomment-145665645), which makes mysql able to write in the mounted directories. MariaDB however crashes for some other reason: 

```
$ docker-compose logs mariadb
Attaching to debiannginxphpdatabasetestapp_mariadb_1
mariadb_1 | * Working around permission errors locally by making sure that "mysql" uses the same uid and gid as the host volume
mariadb_1 | -- Setting mysql user to use uid 1000
mariadb_1 | -- Setting mysql group to use gid 50
mariadb_1 |
mariadb_1 | * Starting MariaDB
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] mysqld (mysqld 10.1.10-MariaDB-1~jessie) starting as process 20 ...
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Warning] Setting lower_case_table_names=2 because file system for /var/lib/mysql/ is case insensitive
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: Using mutexes to ref count buffer pool pages
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: The InnoDB memory heap is disabled
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: Mutexes and rw_locks use GCC atomic builtins
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: Memory barrier is not used
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: Compressed tables use zlib 1.2.8
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: Using Linux native AIO
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: Using SSE crc32 instructions
mariadb_1 | 2016-01-07 10:44:09 140515454482368 [Note] InnoDB: Initializing buffer pool, size = 256.0M
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Note] InnoDB: Completed initialization of buffer pool
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Warning] InnoDB: Failed to set O_DIRECT on file ./ibdata1: OPEN: Invalid argument, continuing anyway. O_DIRECT is known to result in 'Invalid argument' on Linux on tmpfs, see MySQL Bug#26662.
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Note] InnoDB: Highest supported file format is Barracuda.
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Note] InnoDB: 128 rollback segment(s) are active.
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Note] InnoDB: Waiting for purge to start
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Note] InnoDB:  Percona XtraDB (http://www.percona.com) 5.6.26-76.0 started; log sequence number 1600729
mariadb_1 | 2016-01-07 10:44:10 140514670118656 [Note] InnoDB: Dumping buffer pool(s) not yet started
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Note] Plugin 'FEEDBACK' is disabled.
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [ERROR] Could not open mysql.plugin table. Some plugins may be not loaded
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [Note] Recovering after a crash using tc.log
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [ERROR] Can't init tc log
mariadb_1 | 2016-01-07 10:44:10 140515454482368 [ERROR] Aborting
mariadb_1 |
```

For the exact implementation used, check https://github.com/neam/docker-stack/blob/9a90433a3a29ca24ad93c84f76d7245528b12e63/stacks/debian-php-nginx.database/docker-compose.yml#L105-L114 and https://github.com/neam/docker-stack/blob/9a90433a3a29ca24ad93c84f76d7245528b12e63/stacks/debian-php-nginx.database/stack/mariadb/run.sh

**Comment by Shumkov** [comment]
I have the same problem as @motin. Did you find any solution?

**Comment by motin** [comment]
@Shumkov no, and have not been actively looking due to not using MariaDB on a day-to-day basis

**Comment by edoantonioco** [comment]
remove that tc.log file and start it again

**Comment by cfedersp** [comment]
This question would be moot if pull request 50 is merged. By injecting the uid and gid into the image build, you can match the container's ownership to the host's.
