### ISSUE TITLE
Can't make mariadb read my.cnf mounted by kubernetes

### ISSUE THREAD

**Issue by nvivobume** [docker-library/mariadb#303]
What is the correct way to make mariadb read my.cnf files with this image?
No matter where I mount my file, it is not read by mariadb.

I'm using mariadb:10.3 under kubernetes.

Is there any specific thing I need to do to make mariadb read these files? Any specific permissions that folders and files need to have? Is there any way to debug why they are not being read?

The only way I seem to be able to config mariadb is throught command line arguments.

**Comment by wglambert** [comment]
What about mounting to to `/etc/mysql/my.cnf` that directory works for me, also ensure the file has appropriate permissions

```console
$ docker run -d --rm --name mariadb --network=net -v "$PWD"/my.cnf:/etc/mysql/my.cnf -p 13306:3306 -e MYSQL_ALLOW_EMPTY_PASSWORD=yes mariadb
483e87405d5a020346ea2b8728b509a99b0f88d909c259f30b01ff7a76643fd8

$ docker run -it --rm --network=net mariadb mysql -h mariadb
Welcome to the MariaDB monitor.  Commands end with ; or \g.
Your MariaDB connection id is 8
Server version: 10.4.11-MariaDB-1:10.4.11+maria~bionic mariadb.org binary distribution

Copyright (c) 2000, 2018, Oracle, MariaDB Corporation Ab and others.

Type 'help;' or '\h' for help. Type '\c' to clear the current input statement.

MariaDB [(none)]>
```

**Comment by yosifkit** [comment]
>The startup configuration is specified in the file `/etc/mysql/my.cnf`, and that file in turn includes any files found in the `/etc/mysql/conf.d` directory that end with `.cnf`. Settings in files in this directory will augment and/or override settings in `/etc/mysql/my.cnf`. If you want to use a customized MySQL configuration, you can create your alternative configuration file in a directory on the host machine and then mount that directory location as `/etc/mysql/conf.d` inside the `mariadb` container.
>
> \- [docker hub docs](https://github.com/docker-library/docs/tree/bdbefab06e1a2aa2ce09566776cfe56c8a3559e5/mariadb#using-a-custom-mysql-configuration-file)

Please ensure that the `mysql` user of the container can access the file.
