### ISSUE TITLE
DB connection issue for PHP/Java (MDEV-24121)

### ISSUE THREAD

**Issue by jliebert** [docker-library/mariadb#332]
Hello,

can you upgrade Docker image with version 10.2.36, 10.3.27, 10.4.17, 10.5.8 ?
This will resolve the serious issue https://jira.mariadb.org/browse/MDEV-24121.

Regards

**Comment by yosifkit** [comment]
Once they are all actually available via the MariaDB `apt` repo, the automated `update.sh` job linked in the readme will commit the updated Dockerfiles here and then [the rest](https://github.com/docker-library/mariadb/tree/1c8ad664ca320bebc8fa105cb3ec9ad385f0bae3#see-a-change-merged-here-that-doesnt-show-up-on-docker-hub-yet).

**Comment by yosifkit** [comment]
They should be built and pushed to Docker Hub soon: https://github.com/docker-library/official-images/pull/9067
