### ISSUE TITLE
Use custom port

### ISSUE THREAD

**Issue by Vadim-Zenin** [docker-library/mariadb#334]
Hello,

Feature request:

Could be possible to use **custom port** instead of 3306 please?
The custom port number could be specified in env MYSQL_PORT for example.

**Comment by wglambert** [comment]
What would be the reasons for wanting a variable for setting this, you can provide your own config https://github.com/docker-library/docs/tree/master/mariadb#using-a-custom-mysql-configuration-file

**Comment by tianon** [comment]
Indeed -- the simplest way to accomplish the specific configuration you're asking for is the `--port` flag to the daemon:

```console
$ docker run ... mariadb:xxx --port 3307
...
Version: 'xxx'  socket: '/var/run/mysqld/mysqld.sock'  port: 3307  mariadb.org binary distribution
```

**Comment by yosifkit** [comment]
Apparently MariaDB also just supports a environment value for this directly:
```console
$ docker run -it --rm mariadb --verbose --help
...
  -P, --port=#        Port number to use for connection or 0 to default to,
                      my.cnf, $MYSQL_TCP_PORT, /etc/services, built-in default
                      (3306), whatever comes first
```
