### ISSUE TITLE
Not working on RPI4

### ISSUE THREAD

**Issue by bd8392** [docker-library/mariadb#335]
Hi :-) I tried to use official image on Raspberry pi 4, but it's not working...I get this weird wrong architecture logs...

**Comment by tianon** [comment]
The tags of this image do support ARM, but only ARM64 (not ARM32), so this will _not_ work if your RPi4 is running Raspbian, but should work if it's running arm64 Ubuntu, Debian, etc.

**Comment by bd8392** [comment]
Oh...sadly I'm running hypriot-os (which is based on raspberian)...thanks for the help :-). Will there be a 32 version?

**Comment by tianon** [comment]
Probably not, but would be a better question for MariaDB upstream, unfortunately.

**Comment by bd8392** [comment]
Okay thanks :-)
