### ISSUE TITLE
Publish MariaDB 10.1

### ISSUE THREAD

**Issue by nazar-pc** [docker-library/mariadb#36]
Since MariaDB 10.1.10 now working fine under Docker (I've tested it even with replication) and repository includes scripts for MariaDB 10.1 I think it is time to publish 10.1.10 tag, update readme on Docker Hub and make 10.1 tag pointing to 10.1.10 build.
I have dependent image and thought that 10.1.10 is already there, but build failed because 10.1 is in fact still 10.1.3.

**Comment by tianon** [comment]
This needs a PR to https://github.com/docker-library/official-images
(specifically "library/mariadb") with the output of the
"generate-stackbrew-library.sh" script from a checkout of this repo. :+1:

**Comment by nazar-pc** [comment]
Can you do that as repo owner?

**Comment by tianon** [comment]
Yes, and I will if nobody else does, but if I do it won't be until Monday,
which is why I suggested that someone else might do it since they could
possibly get to making that PR for us sooner.

**Comment by nazar-pc** [comment]
MariaDB 10.1.10 tag is available now, thanks!
