### ISSUE TITLE
No TERM env

### ISSUE THREAD

**Issue by m-radzikowski** [docker-library/mariadb#52]
After creating MariaDB container and logging into shell like this:

```
docker exec -it my-mariadb bash
```

trying to login to mysql results in:

```
root@89dbefe61db1:/# mysql     
TERM environment variable not set.
```

Temporary solution is:

```
export TERM=dumb
```

Better solution is to set it in container configuration, for example:

```
docker run --name my-mariadb -e MYSQL_ROOT_PASSWORD=qwerty -e TERM=dumb -d mariadb:10.1
```

But best solution it would be to have it right in the mariadb image :wink: 

Image: mariadb:10.1, Docker version 1.10.3 build 20f81dd

**Comment by yosifkit** [comment]
Newer Docker will set `TERM` on `docker exec`. Closing old issue.
