### ISSUE TITLE
Database initialization and Galera replication

### ISSUE THREAD

**Issue by itatabitovski** [docker-library/mariadb#60]
Hi,

I've run into this issue and I would like to ask if there is a better way and share my workaround.

I used image mariadb:10 and I have galera related configuration in galera.cnf that I mound in /etc/mysql/conf.d/galera.cnf.

`docker run -v $(pwd)/galera.cnf:/etc/mysql/conf.d mariadb:10`

When starting a new container without any data as soon as the initialization starts galera replication interferes.

My workaround is to change line 49 in the entrypoint script
https://github.com/docker-library/mariadb/blob/master/docker-entrypoint.sh#L49

to:
`"$@" --skip-networking --wsrep_on=OFF &`

This will disable galera replication during initial db setup.

Is there a better way to handle this?

**Comment by macropin** [comment]
Please see PR #57 .

Currently the only is to create an empty `/var/lib/mysql/mysql` directory, which is a bit obscure.

**Comment by itatabitovski** [comment]
Closing this in favor of [#57](https://github.com/docker-library/mariadb/pull/57).

**Comment by tanji** [comment]
See https://gist.github.com/tanji/919c0dca2e3679acecd7d8cf2a3a886e for a complete solution
