### ISSUE TITLE
Option to not initialise database

### ISSUE THREAD

**Issue by foxx** [docker-library/mariadb#66]
Can you please give the option to not initialise the database on startup via an envvar? Otherwise this will not work well with Galera SST, as it attempts to do SST during entrypoint init.

**Comment by yosifkit** [comment]
I think this is accomplished by just skipping the entrypoint script (`--entrypoint mysqld`).  It only provides a few things, most of which you don't want on the cluster node anyway:

- chown /var/lib/mysql
  - if bind mounting a directory from the host, just make sure the permissions are correct
- switch user from root to mysql user
  - just use `--user` on your docker run: `docker run --user mysql ... mysql`
- initdb including root password and user creation from environment variables  (not wanted on a cluster replica)
- run scripts in `/docker-entrypoint-initdb.d/` (also not wanted on the replica)

**Comment by tanji** [comment]
@foxx see https://gist.github.com/tanji/919c0dca2e3679acecd7d8cf2a3a886e for an example of how to do it with compose.

**Comment by foxx** [comment]
Thanks for the solutions! Should this go into the README or something?

**Comment by yosifkit** [comment]
Closing old issue.
