### ISSUE TITLE
Problem with Dockerfile 10.n

### ISSUE THREAD

**Issue by ianbram** [docker-library/mariadb#72]
When trying to build an image using this dockerfile (10.0 & 10.1) I receive the following error.
I even get the error if I create my own docker file with the FROM set as mariadb:latest.

Step 27 : RUN {                 echo mariadb-server-$MARIADB_MAJOR mysql-server/root_password password 'unused';                echo mariadb-server-$MARIADB_MAJOR mysql-server/root_password_again password 'unused';  } | debconf-set-selections   && apt-get update       && apt-get install -y           mariadb-server=$MARIADB_VERSION                 percona-xtrabackup              socat   && rm -rf /var/lib/apt/lists/*  && sed -ri 's/^user\s/#&/' /etc/mysql/my.cnf /etc/mysql/conf.d/*     && rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld     && chown -R mysql:mysql /var/lib/mysql /var/run/mysqld  && chmod 777 /var/run/mysqld
 ---> Running in 727bbd0e2c6a
Get:1 http://security.debian.org jessie/updates InRelease [63.1 kB]
Get:2 http://ftp.osuosl.org jessie InRelease [2488 B]
E: The method driver /usr/lib/apt/methods/https could not be found.
The command '/bin/sh -c {               echo mariadb-server-$MARIADB_MAJOR mysql-server/root_password password 'unused';                echo mariadb-server-$MARIADB_MAJOR mysql-server/root_password_again password 'unused';  } | debconf-set-selections   && apt-get update       && apt-get install -y           mariadb-server=$MARIADB_VERSION                 percona-xtrabackup              socat   && rm -rf /var/lib/apt/lists/*  && sed -ri 's/^user\s/#&/' /etc/mysql/my.cnf /etc/mysql/conf.d/*     && rm -rf /var/lib/mysql && mkdir -p /var/lib/mysql /var/run/mysqld     && chown -R mysql:mysql /var/lib/mysql /var/run/mysqld  && chmod 777 /var/run/mysqld' returned a non-zero code: 100

**Comment by yosifkit** [comment]
This is fixed by https://github.com/docker-library/mariadb/pull/71.
