### ISSUE TITLE
TokuDB Storage Engine Support

### ISSUE THREAD

**Issue by sjmcdowall** [docker-library/mariadb#73]
Although MariaDB has had TokuDB engine support built in for a while -- the docker standard docker containers don't really support it very well.  To whit -- the THP should at least be checked and if not disabled then error out if wanting TokuDB .. 

So maybe have an ENV variable indicating wanting TokuDB (at all) and maybe as the default for new DB's .. and 

1 -- checking THP support 

2 -- Loading the module 

3 -- Setting TokuDB as the default storage engine (extra option ENV maybe?) 

Now granted one can do #2 and #3 fairly easily via additional or new .cnf.d etc. type files, but #1 not so much .. ??

**Comment by yosifkit** [comment]
I really think checking THP support checking is better left in the hands of the user; minimally they should be checking their logs for `'TokuDB'; Plugin initialization function failed` if they are specifically turning on the TokuDB storage engine.

Also, no need for an env; it is as easy as the following:
```console
$ docker run -d --name mysql -e MYSQL_ROOT_PASSWORD=password mariadb --plugin-load=ha_tokudb --default-storage-engine=TokuDB
```

**Comment by sjmcdowall** [comment]
Ok -- I'm still not positive that a "purported" TokuDB container wouldn't give a good error message right away for checking the THP is a good idea .. After 20+ years doing this -- I know a ton of "ops" people who will just complain the container didn't start .. and not bother to figure out why (sadly). 

So my rationale was to reduce this error upfront with a very obvious and pronounced error message up front (it is a TOKUDB package after all).  

As for the plugin ENV .. yay!  Ok -- that is about perfect!  Is that in the doc's though -- it should be because it does make everything easier all around!

**Comment by yosifkit** [comment]
There is nothing specifically in the docs about TokuDB, but there is the section on `Configuration without a cnf file` that talks about adding `mysqld` flags to the end of the `docker run`.

**Comment by denji** [comment]
`mariadb:10.2` TokuDB not installd plugin,  `mariadb:10.1` TokuDB just work fine

```diff
	&& apt-get install -y \
		mariadb-server=$MARIADB_VERSION \
+		mariadb-plugin-aws-key-management-10.2=$MARIADB_VERSION \
+		mariadb-plugin-connect=$MARIADB_VERSION \
+		mariadb-plugin-cracklib-password-check=$MARIADB_VERSION \
+		mariadb-plugin-gssapi-client=$MARIADB_VERSION \
+		mariadb-plugin-gssapi-server=$MARIADB_VERSION \
+		mariadb-plugin-mroonga=$MARIADB_VERSION \
+		mariadb-plugin-oqgraph=$MARIADB_VERSION \
+		mariadb-plugin-rocksdb=$MARIADB_VERSION \
+		mariadb-plugin-spider=$MARIADB_VERSION \
+		mariadb-plugin-tokudb=$MARIADB_VERSION \
```

**Comment by grooverdan** [comment]
FYI TokuDB has been removed from [mariadb](https://jira.mariadb.org/browse/MDEV-19780) from 10.6.0 onwards.
