### ISSUE TITLE
-e variables not executing on startup

### ISSUE THREAD

**Issue by jmorgan415** [docker-library/mariadb#75]
In the docker-entrypoint.sh, everything within this if block does not execute:

if [ ! -d "$DATADIR/mysql" ]; then

I tested by adding an else statement to it and echoing out some random statement, which did execute.  It seems most of the contents within the if block need to execute in order to do things like set the root password being passed in, etc.

Has this been tested? I eliminated the if statements completely, but then mysql won't run at all.

**Comment by yosifkit** [comment]
This is the expected behavior.  This part is only done on the first run of the container with an empty data directory; otherwise it would fail to `mysql_install_db` since it would complain about the non-empty directory.

**Comment by yosifkit** [comment]
Closing old issue.
