### ISSUE TITLE
database not created on startup

### ISSUE THREAD

**Issue by rrva** [docker-library/mariadb#76]
When I specify MYSQL_DATABASE environment variable, database is not auto-created on startup using image mariadb:10.1 9a0138c02438

**Comment by yosifkit** [comment]
The database is only created on the first run of the container if there are [no files](https://github.com/docker-library/mariadb/blob/0bcd1e2db0ef04f4abac85e2a759b04231ba60a0/docker-entrypoint.sh#L36) in `/var/lib/mysql`.  Are you bind mounting a local directory (`-v`) or using docker-compose?

**Comment by rrva** [comment]
ah, I was. I ended up using this:

```
FROM mariadb:10.1
COPY *.sql /docker-entrypoint-initdb.d/
```

**Comment by rrva** [comment]
Closing, but would be nice to mention the above in README.md. Judging from comments on https://hub.docker.com/_/mariadb/ others seem to have run into this issue as well.
