### ISSUE TITLE
Change download url to not use a fixed mirror

### ISSUE THREAD

**Issue by J0WI** [docker-library/mariadb#79]
Currently the mirror of the Oregon State University is used to download the MariaDB packages.
I wonder why a mirror is used at all here?

I didn't found the original sources for Debian Packages, maybe MariaDB can be asked for that.

The generic packed sources can be found on [GitHub](https://github.com/MariaDB/server/releases) or on `https://downloads.mariadb.org/f/mariadb-$VERSION/source/mariadb-$VERSION.tar.gz` which redirects to a mirror near you.

**Comment by yosifkit** [comment]
That would only help if we were downloading the source tar file, but we are using their deb repo, so we have to choose a mirror: https://downloads.mariadb.org/mariadb/repositories/#mirror=accretive&distro=Debian&distro_release=jessie--jessie&version=10.1.  :cry:

**Comment by J0WI** [comment]
But where are the mirrors getting their sources from?

**Comment by tanji** [comment]
They get their sources from a non-public facing mirror, because obviously mariadb.org doesn't have as much bandwidth as the mirrors do.
Would it help to have a generic URL that picks up the closest mirror?

**Comment by tanji** [comment]
The Oregon State University mirror is the primary mirror for MariaDB.
All other mirrors pull from it.

**Comment by yosifkit** [comment]
Closing old issue.

**Comment by J0WI** [comment]
Sadly without any resolution.
