### ISSUE TITLE
leap-seconds.list missing

### ISSUE THREAD

**Issue by strarsis** [docker-library/mariadb#91]
Same as with mysql: https://github.com/docker-library/mysql/issues/229

During start up:
````
[...]
Warning: Unable to load '/usr/share/zoneinfo/leap-seconds.list' as time zone. Skipping it.
[...]
````
Installing the Debian tzdata package resolves the issue.

**Comment by tianon** [comment]
Sorry for the delay!

As I noted over in https://github.com/docker-library/mysql/issues/229#issuecomment-342710196, the `tzdata` package is already installed in this image (and is actually exactly the reason this warning is emitted).

However (also as noted there), the warning itself is harmless, and should be ignored. :+1:
